import React,{useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {Check,ChevronDown,Globe2} from "lucide-react";
import headlogoImg from "../../assets/cortexa/headlogo.png";
import {useAuth} from "../../context/AuthContext";
import {trackEvent} from "../../utils/track";
import "./FreeWebsiteReview.css";

const API_BASE="https://backend.cortexaaicrm.com";
const HREFS=["/#features","/#ai-assistant","/#automation","/#pipeline","/#analytics","/pricing","/editorial/the-end-of-legacy-crm","/web-solutions","/trial?flow=free-access&plan=free"];
const COPY={
en:{nav:["Features","AI Assistant","AI Workflows","Pipeline","Analytics","Pricing","Cost Calculator","Web Solutions","Get Started"],hero:["FREE WEBSITE REVIEW","Tell us about your website.","Share your website and business goals. Our team will review your current experience, identify missing functionality and conversion opportunities, and contact you within 24 hours with the next steps.","No payment","required."],fields:["Full name","Business name","Business email","Phone number with country code","Website URL","Current website platform","Select a platform","What would you like to improve?","What is currently not working or limiting your website?","What result would you like this project to achieve?","Systems or tools that need to connect","optional","Preferred contact method"],opts:["Design and user experience","Appointments","CRM connection","Checkout or payments","AI agent integration","Automation and workflows","Lead capture","Analytics and tracking","WhatsApp or phone","Other"],place:["John Smith","Your business name","you@yourbusiness.com","+1 (555) 123-4567","https://www.yourwebsite.com","Tell us about the main challenges, issues, or limitations you're experiencing...","Share your goals, expected outcomes, or what success looks like for you...","e.g. CRM, email marketing, payment processor, etc."],contact:["Email","Phone","WhatsApp"],auth:"I authorize Cortexa to review the website URL provided and contact me regarding this request.",submit:"Submit Website for Free Review",submitting:"Submitting...",note:["Our team will review your submission and contact you within 24 hours.","Submitting this form does not create a payment or purchase obligation."],next:["What happens next",["We review your website","Our team will evaluate your current website, user experience, and setup."],["We identify priorities and opportunities","We'll pinpoint what's working well and where you can improve functionality, integrations, conversions."],["We contact you with recommendations and a custom quotation","You'll receive a personalized summary and next steps within 24 hours."]],success:["Your website review request has been submitted.","Our team will review your submission and contact you within 24 hours.","Back to Web Solutions"],errors:["Please complete all required fields.","Unable to submit your website review request."],footer:["© 2026 Cortexa. All rights reserved.","Privacy","Terms","Contact","Dashboard","Log in"]},
es:{nav:["Funciones","Asistente IA","Flujos de IA","Pipeline","Analítica","Precios","Calculadora de Costes","Soluciones Web","Comenzar"],hero:["REVISIÓN GRATUITA DEL SITIO WEB","Cuéntanos sobre tu sitio web.","Comparte tu sitio web y los objetivos de tu negocio. Nuestro equipo revisará tu experiencia actual, identificará funcionalidades faltantes y oportunidades de conversión, y se pondrá en contacto contigo dentro de 24 horas con los próximos pasos.","No se requiere","ningún pago."],fields:["Nombre completo","Nombre de la empresa","Email empresarial","Número de teléfono con código de país","URL del sitio web","Plataforma actual del sitio web","Selecciona una plataforma","¿Qué te gustaría mejorar?","¿Qué no funciona actualmente o limita tu sitio web?","¿Qué resultado te gustaría lograr con este proyecto?","Sistemas o herramientas que deben conectarse","opcional","Método de contacto preferido"],opts:["Diseño y experiencia de usuario","Citas","Conexión con CRM","Checkout o pagos","Integración con agentes de IA","Automatización y flujos de trabajo","Captura de leads","Analítica y seguimiento","WhatsApp o teléfono","Otro"],place:["John Smith","Nombre de tu empresa","tu@empresa.com","+1 (555) 123-4567","https://www.tusitioweb.com","Cuéntanos los principales desafíos, problemas o limitaciones que estás experimentando...","Comparte tus objetivos, resultados esperados o cómo sería el éxito para ti...","p. ej. CRM, email marketing, procesador de pagos, etc."],contact:["Email","Teléfono","WhatsApp"],auth:"Autorizo a Cortexa a revisar la URL del sitio web proporcionada y a contactarme en relación con esta solicitud.",submit:"Enviar sitio web para revisión gratuita",submitting:"Enviando...",note:["Nuestro equipo revisará tu solicitud y se pondrá en contacto contigo dentro de 24 horas.","Enviar este formulario no crea ninguna obligación de pago o compra."],next:["Qué sucede después",["Revisamos tu sitio web","Nuestro equipo evaluará tu sitio web actual, la experiencia de usuario y la configuración."],["Identificamos prioridades y oportunidades","Identificaremos qué funciona bien y dónde puedes mejorar funcionalidad, integraciones y conversiones."],["Te contactamos con recomendaciones y una cotización personalizada","Recibirás un resumen personalizado y los próximos pasos dentro de 24 horas."]],success:["Tu solicitud de revisión del sitio web ha sido enviada.","Nuestro equipo revisará tu solicitud y se pondrá en contacto contigo dentro de 24 horas.","Volver a Soluciones Web"],errors:["Completa todos los campos obligatorios.","No se pudo enviar tu solicitud de revisión."],footer:["© 2026 Cortexa. Todos los derechos reservados.","Privacidad","Términos","Contacto","Panel","Iniciar sesión"]},
pt:{nav:["Recursos","Assistente IA","Fluxos de IA","Pipeline","Análises","Preços","Calculadora de Custos","Soluções Web","Começar"],hero:["ANÁLISE GRATUITA DO SITE","Conte-nos sobre o seu site.","Compartilhe seu site e os objetivos do seu negócio. Nossa equipe analisará sua experiência atual, identificará funcionalidades ausentes e oportunidades de conversão e entrará em contato em até 24 horas com os próximos passos.","Nenhum pagamento é","necessário."],fields:["Nome completo","Nome da empresa","E-mail comercial","Número de telefone com código do país","URL do site","Plataforma atual do site","Selecione uma plataforma","O que você gostaria de melhorar?","O que atualmente não está funcionando ou está limitando seu site?","Que resultado você gostaria que este projeto alcançasse?","Sistemas ou ferramentas que precisam ser conectados","opcional","Método de contato preferido"],opts:["Design e experiência do usuário","Agendamentos","Conexão com CRM","Checkout ou pagamentos","Integração com agentes de IA","Automação e fluxos de trabalho","Captura de leads","Análises e rastreamento","WhatsApp ou telefone","Outro"],place:["John Smith","Nome da sua empresa","voce@suaempresa.com","+1 (555) 123-4567","https://www.seusite.com","Conte-nos sobre os principais desafios, problemas ou limitações que você está enfrentando...","Compartilhe seus objetivos, resultados esperados ou como seria o sucesso para você...","ex.: CRM, e-mail marketing, processador de pagamentos etc."],contact:["E-mail","Telefone","WhatsApp"],auth:"Autorizo a Cortexa a analisar a URL do site fornecida e entrar em contato comigo sobre esta solicitação.",submit:"Enviar site para análise gratuita",submitting:"Enviando...",note:["Nossa equipe analisará sua solicitação e entrará em contato em até 24 horas.","O envio deste formulário não cria obrigação de pagamento ou compra."],next:["O que acontece depois",["Analisamos seu site","Nossa equipe avaliará seu site atual, a experiência do usuário e a configuração."],["Identificamos prioridades e oportunidades","Vamos identificar o que está funcionando bem e onde você pode melhorar funcionalidades, integrações e conversões."],["Entramos em contato com recomendações e um orçamento personalizado","Você receberá um resumo personalizado e os próximos passos em até 24 horas."]],success:["Sua solicitação de análise do site foi enviada.","Nossa equipe analisará sua solicitação e entrará em contato em até 24 horas.","Voltar para Soluções Web"],errors:["Preencha todos os campos obrigatórios.","Não foi possível enviar sua solicitação de análise."],footer:["© 2026 Cortexa. Todos os direitos reservados.","Privacidade","Termos","Contato","Painel","Entrar"]}
};
function Language({lang,setLang,footer=false}){const[open,setOpen]=useState(false);return <div className={`fwr-language ${footer?"fwr-language-footer":""}`}><button type="button" className="fwr-language-button" onClick={()=>setOpen(v=>!v)}><Globe2 size={18}/></button>{open&&<div className="fwr-language-menu">{[["en","English"],["es","Español"],["pt","Português"]].map(([v,l])=><button key={v} className={lang===v?"active":""} onClick={()=>{setLang(v);setOpen(false)}}>{l}</button>)}</div>}</div>}
function HeaderFooter({tr,lang,setLang,footer=false}){const{isAuthenticated}=useAuth();if(!footer)return <header className="fwr-header"><div className="fwr-header-inner"><Link to="/" className="fwr-brand"><img src={headlogoImg} alt="Cortexa Agentic CRM"/></Link><nav>{tr.nav.map((l,i)=><a key={i} href={HREFS[i]} className={i===7?"active":""}>{l}</a>)}</nav><div className="fwr-actions"><Language lang={lang} setLang={setLang}/><a href={isAuthenticated?"/dashboard/home":"/sign-in"}>{isAuthenticated?tr.footer[4]:tr.footer[5]}</a></div></div></header>;return <footer className="fwr-footer"><div className="fwr-container fwr-footer-main"><Link to="/" className="fwr-brand"><img src={headlogoImg} alt="Cortexa Agentic CRM"/></Link><nav>{tr.nav.map((l,i)=><a key={i} href={HREFS[i]}>{l}</a>)}</nav><div className="fwr-actions"><Language lang={lang} setLang={setLang} footer/><a href={isAuthenticated?"/dashboard/home":"/sign-in"}>{isAuthenticated?tr.footer[4]:tr.footer[5]}</a></div></div><div className="fwr-container fwr-footer-bottom"><span>{tr.footer[0]}</span><div><a href="/privacy-policy">{tr.footer[1]}</a><a href="/terms">{tr.footer[2]}</a><a href="mailto:support@cortexaaicrm.com">{tr.footer[3]}</a></div></div></footer>}
export default function FreeWebsiteReview(){
 const[lang,setLangState]=useState(()=>localStorage.getItem("cortexa_lang")||"en");const tr=COPY[lang]||COPY.en;
 const setLang=(v)=>{setLangState(v);localStorage.setItem("cortexa_lang",v);localStorage.setItem("cortexa_locale",v);document.documentElement.lang=v==="pt"?"pt-BR":v};useEffect(()=>{document.documentElement.lang=lang==="pt"?"pt-BR":lang},[lang]);
 const[form,setForm]=useState({fullName:"",businessName:"",email:"",phone:"",websiteUrl:"",platform:"",improvements:[],limitations:"",goal:"",systems:"",contactMethod:"email",authorized:false});const[loading,setLoading]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(false);
 const update=k=>e=>setForm(p=>({...p,[k]:e.target.type==="checkbox"?e.target.checked:e.target.value}));const toggle=v=>setForm(p=>({...p,improvements:p.improvements.includes(v)?p.improvements.filter(x=>x!==v):[...p.improvements,v]}));
 const submit=async e=>{e.preventDefault();setError("");if(!form.fullName.trim()||!form.businessName.trim()||!form.email.trim()||!form.phone.trim()||!form.websiteUrl.trim()||!form.platform||!form.improvements.length||!form.limitations.trim()||!form.goal.trim()||!form.authorized){setError(tr.errors[0]);return}setLoading(true);try{const r=await fetch(`${API_BASE}/api/web-solutions/free-review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.success)throw new Error(d?.message||tr.errors[1]);trackEvent("free_professional_review_request",{page_path:window.location.pathname,language:lang,has_website:Boolean(form.websiteUrl.trim())});setSuccess(true);window.scrollTo({top:0,behavior:"smooth"})}catch(e){setError(e?.message||tr.errors[1])}finally{setLoading(false)}};
 return <div className="fwr-page"><HeaderFooter tr={tr} lang={lang} setLang={setLang}/><main><section className="fwr-hero"><div className="fwr-eyebrow">{tr.hero[0]}</div><h1>{tr.hero[1]}</h1><p>{tr.hero[2]}</p><div className="fwr-no-payment"><span><Check size={18}/></span>{tr.hero[3]} <b>{tr.hero[4]}</b></div></section><div className="fwr-container">
 {success?<section className="fwr-success"><span><Check size={30}/></span><h2>{tr.success[0]}</h2><p>{tr.success[1]}</p><Link to="/web-solutions">{tr.success[2]}</Link></section>:
 <section className="fwr-panel"><form onSubmit={submit} className="fwr-form"><div className="fwr-two">
 <label>{tr.fields[0]} <em>*</em><input value={form.fullName} onChange={update("fullName")} placeholder={tr.place[0]}/></label><label>{tr.fields[1]} <em>*</em><input value={form.businessName} onChange={update("businessName")} placeholder={tr.place[1]}/></label>
 <label>{tr.fields[2]} <em>*</em><input type="email" value={form.email} onChange={update("email")} placeholder={tr.place[2]}/></label><label>{tr.fields[3]} <em>*</em><input value={form.phone} onChange={update("phone")} placeholder={tr.place[3]}/></label>
 <label>{tr.fields[4]} <em>*</em><input value={form.websiteUrl} onChange={update("websiteUrl")} placeholder={tr.place[4]}/></label><label>{tr.fields[5]}<select value={form.platform} onChange={update("platform")}><option value="">{tr.fields[6]}</option>{["WordPress","Shopify","Webflow","Wix","Squarespace","Custom","Other"].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <fieldset className="fwr-checks"><legend>{tr.fields[7]} <em>*</em></legend><div>{tr.opts.map((item,i)=><label key={item}><input type="checkbox" checked={form.improvements.includes(item)} onChange={()=>toggle(item)}/><span>{item}</span></label>)}</div></fieldset>
 <label>{tr.fields[8]} <em>*</em><textarea value={form.limitations} onChange={update("limitations")} placeholder={tr.place[5]}/></label><label>{tr.fields[9]} <em>*</em><textarea value={form.goal} onChange={update("goal")} placeholder={tr.place[6]}/></label>
 <div className="fwr-bottom-fields"><label>{tr.fields[10]} <small>({tr.fields[11]})</small><input value={form.systems} onChange={update("systems")} placeholder={tr.place[7]}/></label><fieldset><legend>{tr.fields[12]}</legend><div className="fwr-radios">{["email","phone","whatsapp"].map((v,i)=><label key={v}><input type="radio" name="contactMethod" value={v} checked={form.contactMethod===v} onChange={update("contactMethod")}/><span>{tr.contact[i]}</span></label>)}</div></fieldset></div>
 <label className="fwr-authorize"><input type="checkbox" checked={form.authorized} onChange={update("authorized")}/><span>{tr.auth} <em>*</em></span></label>{error&&<div className="fwr-error">{error}</div>}<button className="fwr-submit" disabled={loading}>{loading?tr.submitting:tr.submit} <span>→</span></button><p className="fwr-form-note">{tr.note[0]}<br/>{tr.note[1]}</p></form>
 <aside className="fwr-next"><h2>{tr.next[0]}</h2>{tr.next.slice(1).map(([t,p],i)=><article key={t}><span>{i+1}</span><div><h3>{t}</h3><p>{p}</p></div></article>)}</aside></section>}</div></main><HeaderFooter tr={tr} lang={lang} setLang={setLang} footer/></div>
}
