import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import {
  ArrowRight, BarChart3, Bot, Box, Check, Code2, FileSearch, Gift, ChevronRight,
  Globe2, Menu, Monitor, Network, Pencil, RefreshCw, Rocket, Settings,
  Shield, SlidersHorizontal, Target, UsersRound, X, CalendarDays, CreditCard, Headphones, LayoutDashboard, UserRound, Bell, ChartNoAxesColumnIncreasing, CircleHelp, Wrench, ClipboardCheck,
} from "lucide-react";
import headlogoImg from "../../assets/cortexa/headlogo.png";
import footdarklogoImg from "../../assets/cortexa/headlogotran.png";
import { useAuth } from "../../context/AuthContext";
import { trackEvent } from "../../utils/track";
import telehealthImg from "./web-solutions-telehealth.png";
import "./WebSolutions.css";

const REVIEW_PATH = "/web-solutions/free-review";
const HREFS = ["/#features","/#ai-assistant","/#automation","/#pipeline","/#analytics","/pricing","/editorial/the-end-of-legacy-crm","/web-solutions","/trial?flow=free-access&plan=free"];

const COPY = {
  en: {
    nav:["Features","AI Assistant","AI Workflows","Pipeline","Analytics","Pricing","Cost Calculator","Web & Software Development|Systems Integration","Get Started"],
    hero:{eyebrow:"CORTEXA WEB & SOFTWARE DEVELOPMENT",title1:"SOFTWARE DEVELOPMENT +",title2:"SYSTEMS INTEGRATION",gradient:"Design. Develop. Modernize. Connect.",desc:"We build and improve websites, digital products, customer portals, and business software—then connect them to your CRM, AI agent, payments, appointments, communications, automation, and data.",lead:"Start with a free professional evaluation.",button:"Request Your Free Evaluation",note:"No payment. No obligation."},
    trust:[["Website + technology assessment","We start with your website to understand your goals, audience, and current setup."],["Built around your business","Recommendations are tailored to your industry, tools, and growth goals."],["Clear scope before development","You’ll know exactly what we’ll build, why it matters, and what it will cost."]],
    design:{title:"What We Design, Develop, and Connect.",lead:"From a professional website to a connected business platform, every solution is designed around how your company operates and grows.",items:[["Web Development","Professional websites, landing pages, e-commerce experiences, and responsive web platforms."],["Custom Software Development","Business applications, customer portals, dashboards, and purpose-built internal systems."],["Digital Product Engineering","Product strategy, UX/UI, prototypes, MVPs, frontend, backend, testing, and deployment."],["Redesign + Modernization","Improve outdated websites and platforms for better design, mobile usability, speed, and conversion."],["CRM, AI + Systems Integration","Connect customer records, AI agents, payments, scheduling, communications, analytics, and existing tools."],["APIs + Automation","Connect systems and automate lead routing, follow-ups, notifications, tasks, and customer journeys."]]},
    build:{title:"Build New—or Modernize What You Already Have.",leftTitle:"Build Something New",left:["Business websites","Web applications","Customer portals","Internal platforms","MVPs and digital products","E-commerce systems"],rightTitle:"Modernize What Exists",right:["Website redesign","Platform restructuring","Mobile optimization","Performance improvements","New functionality","CRM, AI, payment, and scheduling integrations"],note:"We build, rebuild, improve, and connect—according to what your business actually needs."},
    outcomes:{eyebrow:"BUILT FOR BUSINESS OUTCOMES",title:"Technology Should Do More Than Look Impressive.",lead:"Every solution should improve how customers experience your business and how your team operates behind the scenes. We connect strategy, design, software, and automation around measurable business needs.",items:[["Create Better Customer Experiences","Build clear, intuitive journeys that help people understand your value, find what they need, and take the next step."],["Improve Operational Efficiency","Connect systems, reduce repetitive work, and give your team better visibility across customers, tasks, communications, and results."],["Prepare for Sustainable Growth","Develop flexible digital foundations that can support new services, integrations, users, locations, and customer demand."]],note:"Built around the way your business works—not around a generic template."},
    lifecycle:{eyebrow:"FROM DIRECTION TO DELIVERY",title:"A Development Partner for the Complete Lifecycle.",lead:"We help define what should be built, choose the right approach, execute the work, connect the required systems, and support the solution as your business evolves.",items:[["Strategy + Discovery","Understand the business, audience, existing technology, operational challenges, and strongest opportunities before development begins."],["Experience + Product Design","Translate requirements into clear customer journeys, thoughtful interfaces, practical functionality, and a cohesive digital experience."],["Engineering + Integration","Develop the frontend, backend, APIs, automation, and system connections required to make the solution work as one."],["Launch + Continued Improvement","Test, deploy, monitor, maintain, and expand the solution as new needs, integrations, and opportunities emerge."]],strip:[["Designed around your operation","Solutions that fit how your business works."],["Clear deliverables and project scope","You’ll know what’s included before we build."],["Built to connect, evolve, and scale","A stronger foundation for long-term growth."]]},
    review:{title:"Start with a free professional review.",lead:"Send us your website URL or tell us what you want to build. Our team will review your current experience, technology, missing functionality, integrations, and conversion opportunities.",free:"Your professional review is free.",price:"If you choose to proceed, professional development services start at",button:"Request Your Free Review",items:[["Website + Technology Assessment","A review of your current website and technology setup."],["Problems and Opportunities","Key issues, gaps, and areas for improvement."],["Recommended Improvements","Practical suggestions tailored to your business goals."],["Proposed Scope and Quotation","A clear plan with deliverables and a fixed cost."]]},
    footer:["© 2026 Cortexa. All rights reserved.","Privacy","Terms","Contact","Dashboard","Log in"]
  },
  es: null,
  pt: null,
};
COPY.es = {
  ...COPY.en,
  nav:["Funciones","Asistente IA","Flujos de IA","Pipeline","Analítica","Precios","Calculadora de Costes","Desarrollo Web y de Software|Integración de Sistemas","Comenzar"],
  hero:{eyebrow:"DESARROLLO WEB Y DE SOFTWARE CORTEXA",title1:"DESARROLLO DE SOFTWARE +",title2:"INTEGRACIÓN DE SISTEMAS",gradient:"Diseña. Desarrolla. Moderniza. Conecta.",desc:"Creamos y mejoramos sitios web, productos digitales, portales de clientes y software empresarial, y luego los conectamos con tu CRM, agente de IA, pagos, citas, comunicaciones, automatización y datos.",lead:"Comienza con una evaluación profesional gratuita.",button:"Solicita tu Evaluación Gratuita",note:"Sin pago. Sin compromiso."},
  trust:[["Evaluación de sitio web + tecnología","Comenzamos con tu sitio web para entender tus objetivos, audiencia y configuración actual."],["Diseñado alrededor de tu negocio","Las recomendaciones se adaptan a tu industria, herramientas y objetivos de crecimiento."],["Alcance claro antes del desarrollo","Sabrás exactamente qué construiremos, por qué es importante y cuánto costará."]],
  design:{title:"Lo Que Diseñamos, Desarrollamos y Conectamos.",lead:"Desde un sitio web profesional hasta una plataforma empresarial conectada, cada solución se diseña según cómo opera y crece tu empresa.",items:[["Desarrollo Web","Sitios web profesionales, landing pages, experiencias de e-commerce y plataformas web responsivas."],["Desarrollo de Software Personalizado","Aplicaciones empresariales, portales de clientes, dashboards y sistemas internos a medida."],["Ingeniería de Productos Digitales","Estrategia de producto, UX/UI, prototipos, MVP, frontend, backend, pruebas y despliegue."],["Rediseño + Modernización","Mejora sitios y plataformas obsoletas para optimizar diseño, uso móvil, velocidad y conversión."],["CRM, IA + Integración de Sistemas","Conecta registros de clientes, agentes de IA, pagos, programación, comunicaciones, analítica y herramientas existentes."],["APIs + Automatización","Conecta sistemas y automatiza asignación de leads, seguimientos, notificaciones, tareas y recorridos de clientes."]]},
  build:{title:"Construye Algo Nuevo o Moderniza lo Que Ya Tienes.",leftTitle:"Construye Algo Nuevo",left:["Sitios web empresariales","Aplicaciones web","Portales de clientes","Plataformas internas","MVP y productos digitales","Sistemas de e-commerce"],rightTitle:"Moderniza lo Existente",right:["Rediseño de sitios web","Reestructuración de plataformas","Optimización móvil","Mejoras de rendimiento","Nuevas funcionalidades","Integraciones de CRM, IA, pagos y programación"],note:"Construimos, reconstruimos, mejoramos y conectamos según lo que tu negocio realmente necesita."},
  outcomes:{...COPY.en.outcomes,eyebrow:"CREADO PARA RESULTADOS DE NEGOCIO",items:[["Crea Mejores Experiencias para Clientes","Construye recorridos claros e intuitivos que ayuden a las personas a entender tu valor, encontrar lo que necesitan y dar el siguiente paso."],["Mejora la Eficiencia Operativa","Conecta sistemas, reduce trabajo repetitivo y brinda a tu equipo mayor visibilidad de clientes, tareas, comunicaciones y resultados."],["Prepárate para un Crecimiento Sostenible","Desarrolla bases digitales flexibles que soporten nuevos servicios, integraciones, usuarios, ubicaciones y demanda de clientes."]]},
  lifecycle:{eyebrow:"DE LA DIRECCIÓN A LA ENTREGA",title:"Un Socio de Desarrollo para Todo el Ciclo de Vida.",lead:"Ayudamos a definir qué construir, elegir el enfoque adecuado, ejecutar el trabajo, conectar los sistemas necesarios y respaldar la solución mientras tu negocio evoluciona.",items:[["Estrategia + Descubrimiento","Comprende el negocio, la audiencia, la tecnología existente, los desafíos operativos y las mejores oportunidades antes de comenzar el desarrollo."],["Experiencia + Diseño de Producto","Transforma requisitos en recorridos claros, interfaces cuidadas, funcionalidad práctica y una experiencia digital coherente."],["Ingeniería + Integración","Desarrolla frontend, backend, APIs, automatización y conexiones de sistemas para que toda la solución funcione como una sola."],["Lanzamiento + Mejora Continua","Prueba, despliega, monitorea, mantiene y amplía la solución a medida que surgen nuevas necesidades, integraciones y oportunidades."]],strip:[["Diseñado alrededor de tu operación","Soluciones que se adaptan a cómo funciona tu negocio."],["Entregables y alcance del proyecto claros","Sabrás qué está incluido antes de construir."],["Creado para conectar, evolucionar y escalar","Una base más sólida para el crecimiento a largo plazo."]]},
  review:{title:"Empieza con una revisión profesional gratuita.",lead:"Envíanos la URL de tu sitio o cuéntanos qué quieres construir. Nuestro equipo revisará tu experiencia actual, tecnología, funcionalidades faltantes, integraciones y oportunidades de conversión.",free:"Tu revisión profesional es gratuita.",price:"Si decides continuar, los servicios profesionales de desarrollo comienzan en",button:"Solicita tu Revisión Gratuita",items:[["Evaluación de Sitio Web + Tecnología","Una revisión de tu sitio web y configuración tecnológica actual."],["Problemas y Oportunidades","Problemas clave, brechas y áreas de mejora."],["Mejoras Recomendadas","Sugerencias prácticas adaptadas a los objetivos de tu negocio."],["Alcance Propuesto y Cotización","Un plan claro con entregables y costo fijo."]]},
  footer:["© 2026 Cortexa. Todos los derechos reservados.","Privacidad","Términos","Contacto","Panel","Iniciar sesión"]
};
COPY.pt = {
  ...COPY.en,
  nav:["Recursos","Assistente IA","Fluxos de IA","Pipeline","Análises","Preços","Calculadora de Custos","Desenvolvimento Web e de Software|Integração de Sistemas","Começar"],
  hero:{eyebrow:"DESENVOLVIMENTO WEB E DE SOFTWARE CORTEXA",title1:"DESENVOLVIMENTO DE SOFTWARE +",title2:"INTEGRAÇÃO DE SISTEMAS",gradient:"Projete. Desenvolva. Modernize. Conecte.",desc:"Criamos e melhoramos sites, produtos digitais, portais de clientes e software empresarial e depois os conectamos ao seu CRM, agente de IA, pagamentos, agendamentos, comunicações, automação e dados.",lead:"Comece com uma avaliação profissional gratuita.",button:"Solicite Sua Avaliação Gratuita",note:"Sem pagamento. Sem compromisso."},
  trust:[["Avaliação de site + tecnologia","Começamos pelo seu site para entender seus objetivos, público e configuração atual."],["Criado em torno do seu negócio","As recomendações são adaptadas ao seu setor, ferramentas e metas de crescimento."],["Escopo claro antes do desenvolvimento","Você saberá exatamente o que construiremos, por que isso importa e quanto custará."]],
  design:{title:"O Que Projetamos, Desenvolvemos e Conectamos.",lead:"De um site profissional a uma plataforma empresarial conectada, cada solução é projetada em torno de como sua empresa opera e cresce.",items:[["Desenvolvimento Web","Sites profissionais, landing pages, experiências de e-commerce e plataformas web responsivas."],["Desenvolvimento de Software Personalizado","Aplicações empresariais, portais de clientes, dashboards e sistemas internos sob medida."],["Engenharia de Produtos Digitais","Estratégia de produto, UX/UI, protótipos, MVPs, frontend, backend, testes e implantação."],["Redesign + Modernização","Melhore sites e plataformas desatualizados para obter melhor design, uso móvel, velocidade e conversão."],["CRM, IA + Integração de Sistemas","Conecte registros de clientes, agentes de IA, pagamentos, agendamentos, comunicações, análises e ferramentas existentes."],["APIs + Automação","Conecte sistemas e automatize distribuição de leads, acompanhamentos, notificações, tarefas e jornadas de clientes."]]},
  build:{title:"Construa Algo Novo ou Modernize o Que Você Já Tem.",leftTitle:"Construa Algo Novo",left:["Sites empresariais","Aplicações web","Portais de clientes","Plataformas internas","MVPs e produtos digitais","Sistemas de e-commerce"],rightTitle:"Modernize o Que Existe",right:["Redesign de sites","Reestruturação de plataformas","Otimização mobile","Melhorias de desempenho","Novas funcionalidades","Integrações de CRM, IA, pagamentos e agendamento"],note:"Construímos, reconstruímos, melhoramos e conectamos de acordo com o que seu negócio realmente precisa."},
  outcomes:{...COPY.en.outcomes,eyebrow:"CRIADO PARA RESULTADOS DE NEGÓCIO",items:[["Crie Melhores Experiências para Clientes","Crie jornadas claras e intuitivas que ajudem as pessoas a entender seu valor, encontrar o que precisam e dar o próximo passo."],["Melhore a Eficiência Operacional","Conecte sistemas, reduza trabalho repetitivo e dê à sua equipe melhor visibilidade de clientes, tarefas, comunicações e resultados."],["Prepare-se para um Crescimento Sustentável","Desenvolva bases digitais flexíveis que suportem novos serviços, integrações, usuários, locais e demanda de clientes."]]},
  lifecycle:{eyebrow:"DA DIREÇÃO À ENTREGA",title:"Um Parceiro de Desenvolvimento para Todo o Ciclo de Vida.",lead:"Ajudamos a definir o que deve ser construído, escolher a abordagem certa, executar o trabalho, conectar os sistemas necessários e apoiar a solução conforme seu negócio evolui.",items:[["Estratégia + Descoberta","Entenda o negócio, o público, a tecnologia existente, os desafios operacionais e as melhores oportunidades antes do desenvolvimento."],["Experiência + Design de Produto","Transforme requisitos em jornadas claras, interfaces cuidadosas, funcionalidade prática e uma experiência digital coesa."],["Engenharia + Integração","Desenvolva frontend, backend, APIs, automação e conexões de sistemas para fazer a solução funcionar como uma só."],["Lançamento + Melhoria Contínua","Teste, implante, monitore, mantenha e expanda a solução à medida que surgem novas necessidades, integrações e oportunidades."]],strip:[["Projetado em torno da sua operação","Soluções que se adaptam à forma como seu negócio funciona."],["Entregas e escopo do projeto claros","Você saberá o que está incluído antes de construirmos."],["Criado para conectar, evoluir e escalar","Uma base mais forte para crescimento de longo prazo."]]},
  review:{title:"Comece com uma revisão profissional gratuita.",lead:"Envie a URL do seu site ou conte o que deseja construir. Nossa equipe analisará sua experiência atual, tecnologia, funcionalidades ausentes, integrações e oportunidades de conversão.",free:"Sua revisão profissional é gratuita.",price:"Se optar por continuar, os serviços profissionais de desenvolvimento começam em",button:"Solicite Sua Revisão Gratuita",items:[["Avaliação de Site + Tecnologia","Uma análise do seu site atual e da configuração tecnológica."],["Problemas e Oportunidades","Principais problemas, lacunas e áreas de melhoria."],["Melhorias Recomendadas","Sugestões práticas adaptadas aos objetivos do seu negócio."],["Escopo Proposto e Orçamento","Um plano claro com entregas e custo fixo."]]},
  footer:["© 2026 Cortexa. Todos os direitos reservados.","Privacidade","Termos","Contato","Painel","Entrar"]
};

const EXT_COPY = {
  en: {
    outcomesTitle:"Connected Technology for Your Business.", outcomesLead:"We develop websites, software and connected systems that support your customer experience, daily operations and business growth.",
    ongoing:{eyebrow:"AN ONGOING RELATIONSHIP",title:"Your development team. Beyond the launch.",lead:"Continue working with the team that understands your website, software and connected systems.",heading:"Ongoing Website & Brand Management",sub:"Keep your website current, your brand consistent and your systems maintained.",items:[["Website & Content Updates","Pages, offers, product content and customer information."],["Brand Consistency","Visual identity, messaging and presentation."],["Software & Integration Maintenance","Technical fixes, connections and workflow upkeep."],["Continuous Improvements","Agreed enhancements as your business evolves."]]},
    products:{eyebrow:"OUR PRODUCT EXPERIENCE",title:"We build connected business products.",lead:"Use an existing Cortexa CRM foundation and adapt it around your business.",cards:[["Cortexa Agentic CRM","Leads, conversations, pipelines, appointments and team workflows."],["Payments & Subscription CRM","Customers, subscriptions, billing calendars, payment activity and integrations."]]},
    needs:{eyebrow:"SOLVE SPECIFIC BUSINESS NEEDS",title:"What do you need to build?",lead:"Start with a specific business need. We help define the right solution and connect it to your operation.",items:["Customer portals","Subscription platforms","Team dashboards","Booking systems","Support operations","Custom workspace features","Payment integrations","Reporting tools"]},
    work:{title:"Choose how you work with us.",lead:"Choose a defined project or ongoing development capacity.",items:[["Project-Based Development","A separately scoped website, software system, CRM feature or integration.",["Defined scope & deliverables","Project timeline","Testing & handover"]],["Part-Time Development & Management","Scheduled support for website updates, brand management, maintenance and focused improvements.",["Agreed monthly priorities","Technical & integration support","Planned enhancements"]],["Full-Time Dedicated Development","Dedicated development capacity for continuous work and larger requirements.",["Ongoing development priorities","Software & CRM enhancements","Testing & integration work"]]],note:"New websites, software systems and custom CRM builds are scoped separately. Availability and responsibilities are agreed before work begins."},
    process:{eyebrow:"FROM QUESTIONS TO CLARITY",title:"A clear process. A connected result.",items:[["01","Evaluate","Review your goal, current tools, and operational needs."],["02","Define","Agree on scope, priorities, features, and cost."],["03","Design & Build","Create the experience and connect the required systems."],["04","Test & Launch","Verify everything works as intended and prepare for launch."],["05","Maintain & Improve","Continue support and development as your business grows."]]},
    faq:{title:"Start with what you already have.",items:[["Can you improve an existing website or application?","Yes. We can review, redesign, modernize, extend and connect an existing website or application."],["Can you work alongside our existing developers?","Yes. We can work with your internal or external team around a clearly defined scope."],["What is included in monthly support?","Monthly support is agreed around priorities such as updates, maintenance, integrations and planned improvements."],["How do you use our current tools or payment providers?","We review your existing stack first and connect supported tools where practical."],["How are ownership and handoff handled?","Project scope defines deliverables, access, ownership and handoff before development begins."],["Do you offer ongoing brand management and dedicated developers?","Yes. Ongoing website, brand and development arrangements are available based on scope and capacity."]]},
    reviewTitle:"Start with a free professional review.",reviewLead:"Send us your website URL or tell us what you want to build. Our team will review your current experience, technology, missing functionality, integrations, and conversion opportunities."
  },
  es: {
    outcomesTitle:"Tecnología Conectada para Tu Negocio.", outcomesLead:"Desarrollamos sitios web, software y sistemas conectados que apoyan la experiencia del cliente, las operaciones diarias y el crecimiento de tu negocio.",
    ongoing:{eyebrow:"UNA RELACIÓN CONTINUA",title:"Tu equipo de desarrollo. Más allá del lanzamiento.",lead:"Sigue trabajando con el equipo que entiende tu sitio web, software y sistemas conectados.",heading:"Gestión Continua de Sitio Web y Marca",sub:"Mantén tu sitio actualizado, tu marca consistente y tus sistemas en buen estado.",items:[["Actualizaciones Web y de Contenido","Páginas, ofertas, productos e información para clientes."],["Consistencia de Marca","Identidad visual, mensajes y presentación."],["Mantenimiento de Software e Integraciones","Correcciones técnicas, conexiones y mantenimiento de flujos."],["Mejoras Continuas","Mejoras acordadas a medida que evoluciona tu negocio."]]},
    products:{eyebrow:"NUESTRA EXPERIENCIA DE PRODUCTO",title:"Creamos productos empresariales conectados.",lead:"Usa una base existente de Cortexa CRM y adáptala a tu negocio.",cards:[["Cortexa Agentic CRM","Leads, conversaciones, pipelines, citas y flujos de equipo."],["CRM de Pagos y Suscripciones","Clientes, suscripciones, calendarios de cobro, actividad de pagos e integraciones."]]},
    needs:{eyebrow:"RESUELVE NECESIDADES ESPECÍFICAS",title:"¿Qué necesitas construir?",lead:"Empieza con una necesidad concreta. Te ayudamos a definir la solución adecuada y conectarla con tu operación.",items:["Portales de clientes","Plataformas de suscripción","Paneles de equipo","Sistemas de reservas","Operaciones de soporte","Funciones personalizadas del workspace","Integraciones de pagos","Herramientas de reportes"]},
    work:{title:"Elige cómo trabajar con nosotros.",lead:"Elige un proyecto definido o capacidad de desarrollo continua.",items:[["Desarrollo por Proyecto","Sitio web, sistema, función CRM o integración con alcance independiente.",["Alcance y entregables definidos","Cronograma del proyecto","Pruebas y entrega"]],["Desarrollo y Gestión a Tiempo Parcial","Soporte programado para actualizaciones, marca, mantenimiento y mejoras enfocadas.",["Prioridades mensuales acordadas","Soporte técnico e integraciones","Mejoras planificadas"]],["Desarrollo Dedicado a Tiempo Completo","Capacidad dedicada para trabajo continuo y requisitos mayores.",["Prioridades continuas","Mejoras de software y CRM","Pruebas e integraciones"]]],note:"Los nuevos sitios, sistemas y CRM personalizados se cotizan por separado. La disponibilidad y responsabilidades se acuerdan antes de comenzar."},
    process:{eyebrow:"DE PREGUNTAS A CLARIDAD",title:"Un proceso claro. Un resultado conectado.",items:[["01","Evaluar","Revisamos objetivos, herramientas actuales y necesidades."],["02","Definir","Acordamos alcance, prioridades, funciones y costo."],["03","Diseñar y Construir","Creamos la experiencia y conectamos los sistemas."],["04","Probar y Lanzar","Verificamos todo y preparamos el lanzamiento."],["05","Mantener y Mejorar","Continuamos el soporte mientras tu negocio crece."]]},
    faq:{title:"Empieza con lo que ya tienes.",items:[["¿Pueden mejorar un sitio o aplicación existente?","Sí. Podemos revisar, rediseñar, modernizar, ampliar y conectar soluciones existentes."],["¿Pueden trabajar con nuestros desarrolladores actuales?","Sí. Podemos colaborar con tu equipo interno o externo con un alcance claro."],["¿Qué incluye el soporte mensual?","Se acuerda según prioridades: actualizaciones, mantenimiento, integraciones y mejoras."],["¿Cómo usan nuestras herramientas o proveedores de pago actuales?","Primero revisamos tu stack y conectamos las herramientas compatibles cuando sea práctico."],["¿Cómo se gestionan la propiedad y la entrega?","El alcance define entregables, accesos, propiedad y entrega antes del desarrollo."],["¿Ofrecen gestión de marca y desarrolladores dedicados?","Sí. Hay opciones continuas según alcance y capacidad."]]},
    reviewTitle:"Empieza con una revisión profesional gratuita.",reviewLead:"Envíanos la URL de tu sitio o cuéntanos qué quieres construir. Revisaremos experiencia, tecnología, funciones faltantes, integraciones y oportunidades de conversión."
  },
  pt: {
    outcomesTitle:"Tecnologia Conectada para o Seu Negócio.", outcomesLead:"Desenvolvemos sites, software e sistemas conectados que apoiam a experiência do cliente, as operações diárias e o crescimento do negócio.",
    ongoing:{eyebrow:"UM RELACIONAMENTO CONTÍNUO",title:"Sua equipe de desenvolvimento. Além do lançamento.",lead:"Continue trabalhando com a equipe que entende seu site, software e sistemas conectados.",heading:"Gestão Contínua de Site e Marca",sub:"Mantenha seu site atualizado, sua marca consistente e seus sistemas bem mantidos.",items:[["Atualizações de Site e Conteúdo","Páginas, ofertas, produtos e informações para clientes."],["Consistência de Marca","Identidade visual, mensagens e apresentação."],["Manutenção de Software e Integrações","Correções técnicas, conexões e manutenção de fluxos."],["Melhorias Contínuas","Melhorias acordadas conforme seu negócio evolui."]]},
    products:{eyebrow:"NOSSA EXPERIÊNCIA DE PRODUTO",title:"Criamos produtos empresariais conectados.",lead:"Use uma base existente do Cortexa CRM e adapte-a ao seu negócio.",cards:[["Cortexa Agentic CRM","Leads, conversas, pipelines, agendamentos e fluxos de equipe."],["CRM de Pagamentos e Assinaturas","Clientes, assinaturas, calendários de cobrança, atividade de pagamentos e integrações."]]},
    needs:{eyebrow:"RESOLVA NECESSIDADES ESPECÍFICAS",title:"O que você precisa construir?",lead:"Comece com uma necessidade específica. Ajudamos a definir a solução certa e conectá-la à sua operação.",items:["Portais de clientes","Plataformas de assinatura","Painéis de equipe","Sistemas de agendamento","Operações de suporte","Recursos personalizados do workspace","Integrações de pagamento","Ferramentas de relatórios"]},
    work:{title:"Escolha como trabalhar conosco.",lead:"Escolha um projeto definido ou capacidade contínua de desenvolvimento.",items:[["Desenvolvimento por Projeto","Site, sistema, recurso CRM ou integração com escopo separado.",["Escopo e entregas definidos","Cronograma do projeto","Testes e entrega"]],["Desenvolvimento e Gestão em Meio Período","Suporte programado para atualizações, marca, manutenção e melhorias focadas.",["Prioridades mensais acordadas","Suporte técnico e integrações","Melhorias planejadas"]],["Desenvolvimento Dedicado em Tempo Integral","Capacidade dedicada para trabalho contínuo e requisitos maiores.",["Prioridades contínuas","Melhorias de software e CRM","Testes e integrações"]]],note:"Novos sites, sistemas e CRMs personalizados são definidos separadamente. Disponibilidade e responsabilidades são acordadas antes do início."},
    process:{eyebrow:"DE PERGUNTAS À CLAREZA",title:"Um processo claro. Um resultado conectado.",items:[["01","Avaliar","Revisamos objetivos, ferramentas atuais e necessidades."],["02","Definir","Acordamos escopo, prioridades, recursos e custo."],["03","Projetar e Construir","Criamos a experiência e conectamos os sistemas."],["04","Testar e Lançar","Verificamos tudo e preparamos o lançamento."],["05","Manter e Melhorar","Continuamos o suporte enquanto seu negócio cresce."]]},
    faq:{title:"Comece com o que você já tem.",items:[["Vocês podem melhorar um site ou aplicativo existente?","Sim. Podemos revisar, redesenhar, modernizar, ampliar e conectar soluções existentes."],["Podem trabalhar com nossos desenvolvedores atuais?","Sim. Podemos colaborar com sua equipe interna ou externa com um escopo claro."],["O que está incluído no suporte mensal?","O suporte é acordado conforme prioridades, manutenção, integrações e melhorias."],["Como usam nossas ferramentas ou provedores de pagamento atuais?","Primeiro revisamos sua stack e conectamos ferramentas compatíveis quando adequado."],["Como propriedade e entrega são tratadas?","O escopo define entregas, acessos, propriedade e handoff antes do desenvolvimento."],["Oferecem gestão de marca e desenvolvedores dedicados?","Sim. Há opções contínuas conforme escopo e capacidade."]]},
    reviewTitle:"Comece com uma revisão profissional gratuita.",reviewLead:"Envie a URL do seu site ou conte o que deseja construir. Revisaremos experiência, tecnologia, funcionalidades ausentes, integrações e oportunidades de conversão."
  }
};

const DESIGN_ICONS=[Monitor,Code2,Box,RefreshCw,Network,Settings];
const OUTCOME_ICONS=[UsersRound,BarChart3,ArrowRight];
const LIFE_ICONS=[FileSearch,Pencil,Code2,Settings];
const STRIP_ICONS=[Target,FileSearch,BarChart3];
const REVIEW_ICONS=[FileSearch,FileSearch,Bot,FileSearch];

function Language({lang,setLang,footer=false}){
  const [open,setOpen]=useState(false);
  return <div className={`ws-language ${footer?"ws-language-footer":""}`}>
    <button type="button" className="ws-language-button" onClick={()=>setOpen(v=>!v)} aria-label="Language"><Globe2 size={18}/></button>
    {open&&<div className="ws-language-menu">{[["en","English"],["es","Español"],["pt","Português"]].map(([v,l])=><button key={v} className={lang===v?"active":""} onClick={()=>{setLang(v);setOpen(false)}}>{l}</button>)}</div>}
  </div>;
}

function NavLabel({label,desktop=false}){
  const parts=String(label).split("|");
  if(parts.length===1) return label;
  return desktop ? <span className="ws-nav-development-label"><span>{parts[0]}</span><span>{parts[1]}</span></span> : parts.join(" ");
}

function Header({tr,lang,setLang}){
  const {isAuthenticated}=useAuth();
  const [mobileOpen,setMobileOpen]=useState(false);
  return <header className="ws-header">
    <div className="ws-header-inner">
      <Link to="/" className="ws-brand"><picture><source media="(max-width: 1024px)" srcSet={footdarklogoImg}/><img src={headlogoImg} alt="Cortexa Agentic CRM"/></picture></Link>
      <nav className="ws-nav">{tr.nav.map((l,i)=><a key={i} href={HREFS[i]} className={`${i===7?"ws-nav-development active":""}`}><NavLabel label={l} desktop/></a>)}</nav>
      <div className="ws-header-actions"><Language lang={lang} setLang={setLang}/><a href={isAuthenticated?"/dashboard/home":"/sign-in"}>{isAuthenticated?tr.footer[4]:tr.footer[5]}</a></div>
      <button className="ws-menu-btn" type="button" onClick={()=>setMobileOpen(v=>!v)} aria-label="Menu">{mobileOpen?<X/>:<Menu/>}</button>
    </div>
    {mobileOpen&&<div className="ws-mobile-menu">{tr.nav.map((l,i)=><a key={i} href={HREFS[i]} className={i===7?"active":""}><NavLabel label={l}/></a>)}<div className="ws-mobile-menu-bottom"><Language lang={lang} setLang={setLang}/><a href={isAuthenticated?"/dashboard/home":"/sign-in"}>{isAuthenticated?tr.footer[4]:tr.footer[5]}</a></div></div>}
  </header>;
}

function Footer({tr,lang,setLang}){
  const {isAuthenticated}=useAuth();
  return <footer className="ws-footer"><div className="ws-container ws-footer-inner">
    <Link to="/" className="ws-footer-brand"><picture><source media="(max-width: 900px)" srcSet={footdarklogoImg}/><img src={headlogoImg} alt="Cortexa Agentic CRM"/></picture></Link>
    <nav>{tr.nav.map((l,i)=><a key={i} href={HREFS[i]}>{String(l).replace("|"," ")}</a>)}</nav>
    <div className="ws-footer-actions"><Language lang={lang} setLang={setLang} footer/><a href={isAuthenticated?"/dashboard/home":"/sign-in"}>{isAuthenticated?tr.footer[4]:tr.footer[5]}</a></div>
  </div><div className="ws-container ws-footer-bottom"><span>{tr.footer[0]}</span><div><a href="/privacy-policy">{tr.footer[1]}</a><a href="/terms">{tr.footer[2]}</a><a href="/contact">{tr.footer[3]}</a></div></div></footer>;
}

function ReviewButton({children,ctaId,lang}){return <Link className="ws-review-btn" to={REVIEW_PATH} onClick={()=>trackEvent("primary_cta_click",{cta_id:ctaId,cta_text:String(children),page_path:window.location.pathname,language:lang})}><span>{children}</span><ArrowRight size={18}/></Link>}
function CheckList({items}){return <ul>{items.map(x=><li key={x}><Check size={16}/><span>{x}</span></li>)}</ul>}

export default function WebSolutions(){
  const [lang,setLangState]=useState(()=>localStorage.getItem("cortexa_lang")||"en");
  const [openFaq,setOpenFaq]=useState(null);
  const setLang=(v)=>{setLangState(v);localStorage.setItem("cortexa_lang",v);localStorage.setItem("cortexa_locale",v);document.documentElement.lang=v==="pt"?"pt-BR":v};
  useEffect(()=>{document.documentElement.lang=lang==="pt"?"pt-BR":lang},[lang]);
  const tr=COPY[lang]||COPY.en, ex=EXT_COPY[lang]||EXT_COPY.en;
  const needIcons=[UsersRound,CreditCard,BarChart3,CalendarDays,Headphones,LayoutDashboard,CreditCard,ChartNoAxesColumnIncreasing];
  return <div className="ws-page"><Header tr={tr} lang={lang} setLang={setLang}/><main>
    <section className="ws-hero"><div className="ws-container"><div className="ws-eyebrow">{tr.hero.eyebrow}</div><h1>{tr.hero.title1}<br/>{tr.hero.title2}</h1><h2>{tr.hero.gradient}</h2><p>{tr.hero.desc}</p><ReviewButton ctaId="web_solutions_hero_free_evaluation" lang={lang}>{tr.hero.button}</ReviewButton></div></section>
    <section className="ws-trust-strip"><div className="ws-container ws-trust-grid">{tr.trust.map(([t,p],i)=>{const I=[FileSearch,Settings,Shield][i];return <article key={t}><I/><div><b>{t}</b><p>{p}</p></div></article>})}</div></section>
    <section className="ws-section ws-design"><div className="ws-container"><h2>{tr.design.title}</h2><p className="ws-section-lead">{tr.design.lead}</p><div className="ws-design-grid">{tr.design.items.map(([t,p],i)=>{const I=DESIGN_ICONS[i];return <article key={t}><I/><div><h3>{t}</h3><p>{p}</p></div></article>})}</div></div></section>
    <section className="ws-section ws-build"><div className="ws-container"><h2>{tr.build.title}</h2><div className="ws-build-grid"><article><Rocket/><div><h3>{tr.build.leftTitle}</h3><CheckList items={tr.build.left}/></div></article><article><Box/><div><h3>{tr.build.rightTitle}</h3><CheckList items={tr.build.right}/></div></article></div><p className="ws-build-note">{tr.build.note}</p></div></section>
    <section className="ws-section ws-outcomes"><div className="ws-container"><div className="ws-eyebrow">{tr.outcomes.eyebrow}</div><h2>{ex.outcomesTitle}</h2><p className="ws-section-lead">{ex.outcomesLead}</p><div className="ws-outcome-grid">{tr.outcomes.items.map(([t,p],i)=>{const I=OUTCOME_ICONS[i];return <article key={t}><I/><h3>{t}</h3><p>{p}</p></article>})}</div></div></section>
    <section className="ws-ongoing-hero"><div className="ws-container"><div className="ws-eyebrow">{ex.ongoing.eyebrow}</div><h2>{ex.ongoing.title}</h2><p>{ex.ongoing.lead}</p></div></section>
    <section className="ws-section ws-management"><div className="ws-container"><h2>{ex.ongoing.heading}</h2><p className="ws-section-lead">{ex.ongoing.sub}</p><div className="ws-management-grid">{ex.ongoing.items.map(([t,p],i)=>{const I=[FileSearch,Pencil,Settings,BarChart3][i];return <article key={t}><I/><div><h3>{t}</h3><p>{p}</p></div></article>})}</div></div></section>
    <section className="ws-section ws-products"><div className="ws-container"><div className="ws-eyebrow">{ex.products.eyebrow}</div><h2>{ex.products.title}</h2><p className="ws-products-lead">{ex.products.lead}</p><div className="ws-product-grid">{ex.products.cards.map(([t,p],i)=><article key={t}><div className="ws-product-mock"><aside className="ws-product-side"><strong>◇ CORTEXA</strong><span>⌂ Dashboard</span><span className="is-active">{i?"Customers":"Leads"}</span><span>{i?"Subscriptions":"Contacts"}</span><span>{i?"Payments":"Companies"}</span><span>{i?"Invoices":"Opportunities"}</span><span>{i?"Products":"Tasks"}</span><span>Reports</span></aside><div className="ws-product-main"><div className="ws-product-top"><b>{i?"Subscriptions":"Sales Pipeline"}</b><span>•••</span></div>{i?<div className="ws-subscription-list">{["JD","AC","MN","SO"].map(n=><div className="ws-sub-row" key={n}><em>{n}</em><i/><small>Active</small><b>−</b></div>)}</div>:<><div className="ws-pipeline-stats">{[["New Leads","12"],["In Progress","8"],["Proposal","6"],["Closed","14"]].map(([a,b])=><div key={a}><small>{a}</small><b>{b}</b></div>)}</div><div className="ws-pipeline-board">{[0,1,2,3].map(col=><div key={col}>{[0,1,2].slice(0,col===3?2:3).map(row=><i key={row}><span/></i>)}</div>)}</div></>}</div></div><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
    <section className="ws-section ws-needs"><div className="ws-container"><div className="ws-eyebrow">{ex.needs.eyebrow}</div><h2>{ex.needs.title}</h2><p className="ws-section-lead">{ex.needs.lead}</p><div className="ws-needs-grid">{ex.needs.items.map((t,i)=>{const I=needIcons[i];return <article key={t}><I/><b>{t}</b></article>})}</div></div></section>
    <section className="ws-telehealth"><div className="ws-container ws-telehealth-con"><img src={telehealthImg} alt="Cortexa Telehealth software and integrations"/></div></section>
    <section className="ws-lifecycle"><div className="ws-container ws-life-main"><div className="ws-life-intro"><div className="ws-eyebrow">{tr.lifecycle.eyebrow}</div><h2>{tr.lifecycle.title}</h2><p>{tr.lifecycle.lead}</p></div><div className="ws-life-grid">{tr.lifecycle.items.map(([t,p],i)=>{const I=LIFE_ICONS[i];return <article key={t}><I/><div><h3>{t}</h3><p>{p}</p></div></article>})}</div></div><div className="ws-container ws-life-strip">{tr.lifecycle.strip.map(([t,p],i)=>{const I=STRIP_ICONS[i];return <article key={t}><I/><div><h3>{t}</h3><p>{p}</p></div></article>})}</div></section>
    <section className="ws-section ws-work"><div className="ws-container"><h2>{ex.work.title}</h2><p className="ws-section-lead">{ex.work.lead}</p><div className="ws-work-grid">{ex.work.items.map(([t,p,list],i)=>{const I=[FileSearch,RefreshCw,UsersRound][i];return <article key={t}><div className="ws-work-head"><I/><div><h3>{t}</h3><p>{p}</p></div></div><CheckList items={list}/></article>})}</div><p className="ws-build-note">{ex.work.note}</p></div></section>
    <section className="ws-section ws-process"><div className="ws-container"><div className="ws-eyebrow">{ex.process.eyebrow}</div><h2>{ex.process.title}</h2><div className="ws-process-grid">{ex.process.items.map(([n,t,p],i)=>{const I=[FileSearch,SlidersHorizontal,Settings,ClipboardCheck,Wrench][i];return <article key={n}><I/><div><b>{n}</b><h3>{t}</h3><p>{p}</p></div></article>})}</div></div></section>
    <section className="ws-section ws-faq"><div className="ws-container"><h2>{ex.faq.title}</h2><div className="ws-faq-grid">{ex.faq.items.map(([q,a],i)=><article key={q} className={openFaq===i?"open":""}><button onClick={()=>setOpenFaq(openFaq===i?null:i)}><span>{q}</span><ChevronRight size={17}/></button>{openFaq===i&&<p>{a}</p>}</article>)}</div></div></section>
    <section className="ws-dark-review"><div className="ws-container ws-final-review"><div className="ws-final-review-copy"><h2>{ex.reviewTitle}</h2><p>{ex.reviewLead}</p></div><div className="ws-final-review-row"><div className="ws-review-items">{tr.review.items.map(([t,p],i)=>{const I=REVIEW_ICONS[i];return <article key={t}><I/><h3>{t}</h3><p>{p}</p></article>})}</div><ReviewButton ctaId="web_solutions_free_review" lang={lang}>{tr.review.button}</ReviewButton></div></div></section>
  </main><Footer tr={tr} lang={lang} setLang={setLang}/></div>;
}
