import React,{useEffect,useState} from "react";
import {useNavigate,useParams} from "react-router-dom";
import {CalendarDays,MessageCircle,Edit3,UserRound,Mail,Phone,AlertTriangle,HeartPulse,RefreshCw,FileText,Activity,Pill,FlaskConical,Archive,X} from "lucide-react";
import {clinicMedicalApi} from "../../api/clinicMedicalApi";
import "./ClinicMedical.css";
const d=v=>v?new Date(v).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"—";
const dt=v=>v?new Date(v).toLocaleString():"—";
export default function ClinicPatientProfile(){
 const {patientId}=useParams(),nav=useNavigate(),[p,setP]=useState(null),[tab,setTab]=useState("Overview"),[edit,setEdit]=useState(false),[form,setForm]=useState({}),[providers,setProviders]=useState([]),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setError("");try{const r=await clinicMedicalApi.patient(patientId);setP(r?.data??r)}catch(e){setError(e?.response?.data?.message||e?.message||"Could not load patient")}};
 useEffect(()=>{load();clinicMedicalApi.providers().then(r=>setProviders((r?.data??r)||[])).catch(()=>{})},[patientId]);
 if(!p)return <div className="cm"><div className="cm-empty">{error||"Loading patient…"}</div></div>;
 const x=p.patient||{},tabs=["Overview","Appointments","Consultations","Medical History","Medications","Orders & Results","Documents","Billing","Activity"];
 const openEdit=()=>{setForm({name:x.name||"",email:x.email||"",phone:x.phone||"",dateOfBirth:x.dateOfBirth?String(x.dateOfBirth).slice(0,10):"",gender:x.gender||"",emergencyContact:x.emergencyContact||"",emergencyPhone:x.emergencyPhone||"",insuranceProvider:x.insuranceProvider||"",insuranceMemberId:x.insuranceMemberId||"",patientStatus:x.patientStatus||"Active",assignedProviderId:x.assignedProviderId||""});setEdit(true)};
 const saveEdit=async e=>{e.preventDefault();setSaving(true);setError("");try{await clinicMedicalApi.updatePatient(patientId,form);setEdit(false);await load()}catch(e){setError(e?.response?.data?.message||e?.message||"Could not update patient")}finally{setSaving(false)}};
 const archive=async()=>{if(!window.confirm(`Archive ${x.name}? The patient will remain in historical records.`))return;setSaving(true);try{await clinicMedicalApi.archivePatient(patientId);nav("/dashboard/clinic-medical/patients")}catch(e){setError(e?.response?.data?.message||e?.message||"Could not archive patient")}finally{setSaving(false)}};
 const start=async()=>{setSaving(true);try{const c=await clinicMedicalApi.createConsultation({patientId});const z=c?.data??c;nav(`/dashboard/clinic-medical/consultations/${z.id}`)}catch(e){setError(e?.response?.data?.message||e?.message||"Could not start consultation")}finally{setSaving(false)}};
 return <div className="cm profile cm-profile-reference">
  <button className="back" onClick={()=>nav("/dashboard/clinic-medical/patients")}>← Back to Patients</button>{error&&<div className="cm-error">{error}</div>}
  <div className="profile-head"><i>{x.initials}</i><div className="identity"><h1>{x.name} <b>{x.patientStatus||"Active"}</b>{p.alerts?.[0]&&<em><AlertTriangle/> {p.alerts[0].label}</em>}</h1><p><span>▣ MRN {x.medicalRecordNo}</span><span><Phone/>{x.phone||"—"}</span><span><Mail/>{x.email||"—"}</span><span><UserRound/>Assigned Provider: {x.providerName||"Unassigned"}</span></p></div><div className="profile-actions"><button onClick={()=>nav(`/dashboard/whatsapp?workspace_id=clinic-medical&contact_id=${patientId}`)}><MessageCircle/>Send Message</button><button onClick={()=>nav(`/dashboard/calendar?workspace_id=clinic-medical&action=new&contact_id=${patientId}`)}><CalendarDays/>Book Appointment</button><button className="primary" disabled={saving} onClick={start}><FileText/>Start Consultation</button><button onClick={openEdit}><Edit3/>Edit Patient</button></div></div><div className="profile-actions-m"><button onClick={()=>nav(`/dashboard/whatsapp?workspace_id=clinic-medical&contact_id=${patientId}`)}><MessageCircle/>Send Message</button><button onClick={()=>nav(`/dashboard/calendar?workspace_id=clinic-medical&action=new&contact_id=${patientId}`)}><CalendarDays/>Book Appointment</button><button className="primary" disabled={saving} onClick={start}><FileText/>Start Consultation</button><button onClick={openEdit}><Edit3/>Edit Patient</button></div>
  <nav className="profile-tabs">{tabs.map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>
  {tab==="Overview"?<><div className="profile-kpis">{[["Total Appointments",p.stats?.totalAppointments,CalendarDays],["Last Consultation",d(p.stats?.lastConsultation),FileText],["Next Appointment",d(p.stats?.nextAppointment),CalendarDays],["Follow-Up",p.stats?.followUpLabel||"None",RefreshCw]].map(([l,v,I])=><div key={l}><I/><span>{l}<strong>{v}</strong></span></div>)}</div>
   <div className="profile-grid"><section className="cm-panel"><header><h3><UserRound/>Patient Information</h3><button onClick={openEdit}>Edit</button></header><div className="info-grid"><label>Date of Birth<b>{d(x.dateOfBirth)}</b></label><label>Emergency Contact<b>{x.emergencyContact||"—"}</b></label><label>Gender<b>{x.gender||"—"}</b></label><label>Emergency Phone<b>{x.emergencyPhone||"—"}</b></label><label>Phone<b>{x.phone||"—"}</b></label><label>Insurance<b>{x.insuranceProvider||"—"}</b></label><label>Email<b>{x.email||"—"}</b></label><label>Assigned Provider<b>{x.providerName||"Unassigned"}</b></label></div></section><section className="cm-panel"><header><h3><CalendarDays/>Upcoming Appointment</h3><button onClick={()=>setTab("Appointments")}>View All Appointments</button></header>{p.upcomingAppointment?<div className="upcoming"><div className="upcoming-title"><strong>{p.upcomingAppointment.title}</strong><i className={`appointment-badge ${String(p.upcomingAppointment.status||"confirmed").toLowerCase()}`}>{p.upcomingAppointment.status||"Confirmed"}</i></div><div className="upcoming-body"><div><p><CalendarDays/>{d(p.upcomingAppointment.startAt)} · {new Date(p.upcomingAppointment.startAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</p><p><UserRound/>{p.upcomingAppointment.providerName||"Unassigned"}</p><p>⌖ {p.upcomingAppointment.location||"—"}</p></div><button onClick={()=>setTab("Appointments")}>View Appointment</button></div></div>:<div className="cm-empty small">No upcoming appointment.</div>}</section>
   <section className="cm-panel"><header><h3><HeartPulse/>Medical Overview</h3><button onClick={openEdit}>Edit</button></header><div className="medical-three"><div><b>Active Conditions</b>{(p.conditions||[]).length?(p.conditions||[]).map(v=><i key={v.id}>{v.label}</i>):<small>None recorded</small>}</div><div><b>Allergies</b>{(p.alerts||[]).filter(a=>a.type==="allergy").length?(p.alerts||[]).filter(a=>a.type==="allergy").map(v=><i className="red" key={v.id}>{v.label}</i>):<small>None recorded</small>}</div><div><b>Current Medications</b>{(p.medications||[]).filter(m=>m.status==="active").length?(p.medications||[]).filter(m=>m.status==="active").map(v=><i className="blue" key={v.id}>{v.name} {v.dosage}</i>):<small>None recorded</small>}</div></div></section><section className="cm-panel"><header><h3><AlertTriangle/>Follow-Up & Alerts</h3><button onClick={()=>setTab("Activity")}>View All</button></header>{(p.followUps||[]).length?(p.followUps||[]).slice(0,3).map(f=><div className="follow-card" key={f.id}><b>{f.reason}</b><span>{f.instructions||"—"}</span><em>{f.dueLabel}</em></div>):<div className="cm-empty small">No open follow-ups.</div>}</section>
   <section className="cm-panel"><header><h3><FileText/>Recent Consultations</h3><button onClick={()=>setTab("Consultations")}>View All Consultations</button></header><Consultations rows={(p.consultations||[]).slice(0,5)} nav={nav}/></section><section className="cm-panel"><header><h3><Activity/>Recent Activity</h3><button onClick={()=>setTab("Activity")}>View All Activity</button></header><ActivityRows rows={(p.activity||[]).slice(0,5)}/></section></div></>:<TabContent tab={tab} p={p} nav={nav}/>} 
  {edit&&<div className="cm-modal-bg" onMouseDown={()=>!saving&&setEdit(false)}><form className="cm-modal cm-patient-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={saveEdit}><div className="cm-modal-title"><h2>Edit Patient</h2><button type="button" onClick={()=>setEdit(false)}><X/></button></div>{[["name","Full Name","text"],["email","Email","email"],["phone","Phone","text"],["dateOfBirth","Date of Birth","date"],["emergencyContact","Emergency Contact","text"],["emergencyPhone","Emergency Phone","text"],["insuranceProvider","Insurance Provider","text"],["insuranceMemberId","Insurance Member ID","text"]].map(([k,l,t])=><label key={k}>{l}<input type={t} value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Gender<select value={form.gender||""} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">Select</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></label><label>Assigned Provider<select value={form.assignedProviderId||""} onChange={e=>setForm({...form,assignedProviderId:e.target.value})}><option value="">Unassigned</option>{providers.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><div className="cm-modal-actions spread"><button type="button" className="danger-outline" onClick={archive}><Archive/>Archive Patient</button><span/><button type="button" onClick={()=>setEdit(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?"Saving…":"Save Changes"}</button></div></form></div>}
 </div>
}
function Consultations({rows,nav}){return rows.length?<div className="consult-table rich">{rows.map(c=><div key={c.id} onClick={()=>nav(`/dashboard/clinic-medical/consultations/${c.id}`)}><span>{d(c.encounterAt)}</span><span>{c.visitReason||"Consultation"}</span><span>{c.providerName||"—"}</span><span>{c.diagnosis||"—"}</span><i>{c.status}</i></div>)}</div>:<div className="cm-empty small">No consultations yet.</div>}
function ActivityRows({rows}){return rows.length?rows.map(a=><div className="activity-row" key={a.id}><b>{a.title}</b><span>{d(a.createdAt)}</span><small>{a.sub||""}</small></div>):<div className="cm-empty small">No activity yet.</div>}
function TabContent({tab,p,nav}){
 if(tab==="Appointments")return <section className="cm-panel tab-content"><header><h3><CalendarDays/>Appointments</h3></header>{(p.appointments||[]).length?<div className="cm-record-list">{p.appointments.map(a=><article key={a.id}><CalendarDays/><div><b>{a.title}</b><span>{dt(a.startAt)} · {a.providerName||"Unassigned"}</span><small>{a.location||"No location"}</small></div><i className={`status ${a.status}`}>{a.status}</i></article>)}</div>:<div className="cm-empty">No appointments yet.</div>}</section>;
 if(tab==="Consultations")return <section className="cm-panel tab-content"><header><h3><FileText/>Consultations</h3></header><Consultations rows={p.consultations||[]} nav={nav}/></section>;
 if(tab==="Medical History")return <section className="tab-content cm-history-grid"><div className="cm-panel"><header><h3><HeartPulse/>Active Conditions</h3></header><SimpleRows rows={p.conditions} render={v=><><b>{v.label}</b><span>{v.icd10||"No ICD-10"}</span><i>{v.status}</i></>}/></div><div className="cm-panel"><header><h3><AlertTriangle/>Alerts & Allergies</h3></header><SimpleRows rows={p.alerts} render={v=><><b>{v.label}</b><span>{v.reaction||"No reaction recorded"}</span><i>{v.severity||v.type}</i></>}/></div></section>;
 if(tab==="Medications")return <section className="cm-panel tab-content"><header><h3><Pill/>Medications</h3></header><SimpleRows rows={p.medications} render={v=><><b>{v.name}</b><span>{[v.dosage,v.frequency].filter(Boolean).join(" · ")||"—"}</span><i>{v.status}</i></>}/></section>;
 if(tab==="Orders & Results")return <section className="cm-panel tab-content"><header><h3><FlaskConical/>Orders & Results</h3></header><SimpleRows rows={p.orders} render={v=><><b>{v.name||v.label||v.order_type||"Clinical order"}</b><span>{v.result||v.notes||"No result recorded"}</span><i>{v.status||"open"}</i></>}/></section>;
 if(tab==="Activity")return <section className="cm-panel tab-content"><header><h3><Activity/>Activity</h3></header><ActivityRows rows={p.activity||[]}/></section>;
 if(tab==="Billing")return <section className="cm-panel tab-content"><header><h3>Billing</h3></header><div className="billing-summary"><span>Current Patient Balance</span><strong>${Number(p.patient?.balance||0).toFixed(2)}</strong><small>Detailed clinic payment history is not returned by the current patient API.</small></div></section>;
 if(tab==="Documents")return <section className="cm-panel tab-content"><header><h3>Documents</h3></header><div className="cm-empty">No patient document records are returned by the current Clinic API.</div></section>;
 return null;
}
function SimpleRows({rows=[],render}){return rows?.length?<div className="cm-simple-list">{rows.map((v,i)=><article key={v.id||i}>{render(v)}</article>)}</div>:<div className="cm-empty small">No records yet.</div>}