import React,{useEffect,useState} from "react";
import {useNavigate,useParams} from "react-router-dom";
import {CalendarDays,MessageCircle,Edit3,UserRound,Mail,Phone,AlertTriangle,HeartPulse,RefreshCw,FileText,DollarSign,Activity} from "lucide-react";
import {clinicMedicalApi} from "../../api/clinicMedicalApi";
import "./ClinicMedical.css";
const d=v=>v?new Date(v).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"—";
export default function ClinicPatientProfile(){
 const {patientId}=useParams(),nav=useNavigate(),[p,setP]=useState(null),[tab,setTab]=useState("Overview");
 useEffect(()=>{clinicMedicalApi.patient(patientId).then(r=>setP(r?.data??r))},[patientId]);
 if(!p)return <div className="cm"><div className="cm-empty">Loading patient…</div></div>;
 const x=p.patient||{}, tabs=["Overview","Appointments","Consultations","Medical History","Medications","Orders & Results","Documents","Billing","Activity"];
 return <div className="cm profile">
  <button className="back" onClick={()=>nav("/dashboard/clinic-medical/patients")}>← Back to Patients</button>
  <div className="profile-head"><i>{x.initials}</i><div className="identity"><h1>{x.name} <b>{x.patientStatus||"Active"}</b>{p.alerts?.[0]&&<em><AlertTriangle/> {p.alerts[0].label}</em>}</h1><p><span>▣ MRN {x.medicalRecordNo}</span><span><Phone/>{x.phone||"—"}</span><span><Mail/>{x.email||"—"}</span><span><UserRound/>Assigned Provider: {x.providerName||"Unassigned"}</span></p></div><div className="profile-actions"><button onClick={()=>nav(`/dashboard/whatsapp?workspace_id=clinic-medical&contact_id=${patientId}`)}><MessageCircle/>Send Message</button><button onClick={()=>nav(`/dashboard/calendar?workspace_id=clinic-medical&action=new&contact_id=${patientId}`)}><CalendarDays/>Book Appointment</button><button className="primary" onClick={async()=>{const c=await clinicMedicalApi.createConsultation({patientId});const z=c?.data??c;nav(`/dashboard/clinic-medical/consultations/${z.id}`)}}><FileText/>Start Consultation</button><button><Edit3/>Edit Patient</button></div></div>
  <nav className="profile-tabs">{tabs.map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>
  {tab==="Overview"?<><div className="profile-kpis">{[["Total Appointments",p.stats?.totalAppointments,CalendarDays],["Last Consultation",d(p.stats?.lastConsultation),FileText],["Next Appointment",d(p.stats?.nextAppointment),CalendarDays],["Follow-Up",p.stats?.followUpLabel||"None",RefreshCw]].map(([l,v,I])=><div key={l}><I/><span>{l}<strong>{v}</strong></span></div>)}</div>
  <div className="profile-grid"><section className="cm-panel"><header><h3><UserRound/>Patient Information</h3><button>Edit</button></header><div className="info-grid"><label>Date of Birth<b>{d(x.dateOfBirth)}</b></label><label>Emergency Contact<b>{x.emergencyContact||"—"}</b></label><label>Gender<b>{x.gender||"—"}</b></label><label>Emergency Phone<b>{x.emergencyPhone||"—"}</b></label><label>Phone<b>{x.phone||"—"}</b></label><label>Insurance<b>{x.insuranceProvider||"—"}</b></label><label>Email<b>{x.email||"—"}</b></label><label>Assigned Provider<b>{x.providerName||"Unassigned"}</b></label></div></section><section className="cm-panel"><header><h3><CalendarDays/>Upcoming Appointment</h3><button onClick={()=>setTab("Appointments")}>View All Appointments</button></header>{p.upcomingAppointment?<div className="upcoming"><strong>{p.upcomingAppointment.title}</strong><p>{d(p.upcomingAppointment.startAt)} · {new Date(p.upcomingAppointment.startAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</p><p>{p.upcomingAppointment.providerName||"Unassigned"} · {p.upcomingAppointment.location||"—"}</p></div>:<div className="cm-empty small">No upcoming appointment.</div>}</section>
  <section className="cm-panel"><header><h3><HeartPulse/>Medical Overview</h3></header><div className="medical-three"><div><b>Active Conditions</b>{(p.conditions||[]).map(v=><i key={v.id}>{v.label}</i>)}</div><div><b>Allergies</b>{(p.alerts||[]).filter(a=>a.type==="allergy").map(v=><i className="red" key={v.id}>{v.label}</i>)}</div><div><b>Current Medications</b>{(p.medications||[]).filter(m=>m.status==="active").map(v=><i className="blue" key={v.id}>{v.name} {v.dosage}</i>)}</div></div></section><section className="cm-panel"><header><h3><AlertTriangle/>Follow-Up & Alerts</h3></header>{(p.followUps||[]).slice(0,3).map(f=><div className="follow-card" key={f.id}><b>{f.reason}</b><span>{f.instructions}</span><em>{f.dueLabel}</em></div>)}</section>
  <section className="cm-panel"><header><h3><FileText/>Recent Consultations</h3><button onClick={()=>setTab("Consultations")}>View All Consultations</button></header><div className="consult-table">{(p.consultations||[]).slice(0,5).map(c=><div key={c.id}><span>{d(c.encounterAt)}</span><span>{c.visitReason||"Consultation"}</span><span>{c.providerName||"—"}</span><span>{c.diagnosis||"—"}</span><i>{c.status}</i></div>)}</div></section><section className="cm-panel"><header><h3><Activity/>Recent Activity</h3><button onClick={()=>setTab("Activity")}>View All Activity</button></header>{(p.activity||[]).slice(0,5).map(a=><div className="activity-row" key={a.id}><b>{a.title}</b><span>{d(a.createdAt)}</span><small>{a.sub}</small></div>)}</section></div></>:<TabContent tab={tab} p={p}/>}
 </div>
}
function TabContent({tab,p}){const map={Appointments:p.appointments,Consultations:p.consultations,Medications:p.medications,"Orders & Results":p.orders,Activity:p.activity};const rows=map[tab]||[];return <section className="cm-panel tab-content"><header><h3>{tab}</h3></header>{rows.length?<pre>{JSON.stringify(rows,null,2)}</pre>:<div className="cm-empty">No {tab.toLowerCase()} records yet.</div>}</section>}