import React,{useEffect,useState} from "react";
import {useNavigate,useSearchParams} from "react-router-dom";
import {Users,CalendarDays,Mail,ClipboardList,Search,Filter,ArrowUpDown,Download,Plus,MoreVertical} from "lucide-react";
import {clinicMedicalApi} from "../../api/clinicMedicalApi";
import "./ClinicMedical.css";
const date=v=>v?new Date(v).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"—";
export default function ClinicPatients(){
 const nav=useNavigate(),[sp]=useSearchParams(),[rows,setRows]=useState([]),[stats,setStats]=useState({}),[meta,setMeta]=useState({page:1,pages:1,total:0}),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[sort,setSort]=useState("updated_desc"),[loading,setLoading]=useState(true),[show,setShow]=useState(false),[form,setForm]=useState({name:"",email:"",phone:"",dateOfBirth:"",gender:"",emergencyContact:"",emergencyPhone:""});
 const load=(page=1)=>{setLoading(true);Promise.all([clinicMedicalApi.patients({page,limit:7,search,status:status==="all"?"":status,sort,followUp:sp.get("followUp")||""}),clinicMedicalApi.patientStats()]).then(([a,b])=>{const x=a?.data??a,y=b?.data??b;setRows(x.items||[]);setMeta(x.meta||{});setStats(y||{});}).finally(()=>setLoading(false));};
 useEffect(()=>{const t=setTimeout(()=>load(1),250);return()=>clearTimeout(t)},[search,status,sort,sp.toString()]);
 const create=async e=>{e.preventDefault();await clinicMedicalApi.createPatient(form);setShow(false);setForm({name:"",email:"",phone:""});load(1)};
 return <div className="cm patients">
  <div className="cm-top"><div className="cm-heading patient-title"><Plus/><div><h1>Patients</h1><p>Manage patient records, appointments, providers, and follow-up.</p></div></div><div className="cm-actions"><button><Download/>Export Patients</button><button className="primary" onClick={()=>setShow(true)}><Plus/>Add Patient</button></div></div>
  <div className="patient-kpis">{[["Total Patients",stats.totalPatients,Users],["Appointments Today",stats.appointmentsToday,CalendarDays],["Follow-Up Required",stats.followUpRequired,Mail],["Active Care Plans",stats.activeCarePlans,ClipboardList]].map(([l,v,I])=><div key={l}><I/><span>{l}<strong>{v??0}</strong><small>Live clinic data</small></span></div>)}</div>
  <div className="patient-tools"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search patients by name, phone, email, or medical record number..."/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Patients</option><option value="Active">Active</option><option value="Follow-Up">Follow-Up</option><option value="Inactive">Inactive</option></select><button><Filter/>Filters</button><select value={sort} onChange={e=>setSort(e.target.value)}><option value="updated_desc">Sort: Recent</option><option value="name_asc">Name A-Z</option><option value="next_asc">Next Appointment</option></select></div>
  <div className="patients-table"><div className="ptr pth"><span>Patient ↕</span><span>Medical Record No. ↕</span><span>Assigned Provider ↕</span><span>Last Appointment ↕</span><span>Next Appointment ↕</span><span>Follow-Up ↕</span><span>Balance ↕</span><span>Status ↕</span><span/></div>{loading?<div className="cm-empty">Loading patients…</div>:rows.length?rows.map(p=><div className="ptr" key={p.id} onClick={()=>nav(`/dashboard/clinic-medical/patients/${p.id}`)}><span className="patient-cell"><i>{p.initials}</i><b>{p.name}<small>{p.phone||"—"}<br/>{p.email||"—"}</small></b></span><span>{p.medicalRecordNo||"—"}</span><span>{p.providerName||"Unassigned"}</span><span>{date(p.lastAppointment)}</span><span>{date(p.nextAppointment)}<small>{p.nextAppointmentLabel}</small></span><span className={p.followUpRequired?"yes":"no"}>{p.followUpRequired?"Yes":"No"}</span><span>${Number(p.balance||0).toFixed(0)}</span><span><i className={`patient-status ${String(p.patientStatus||"Active").toLowerCase().replaceAll(" ","-")}`}>{p.patientStatus||"Active"}</i></span><span><MoreVertical/></span></div>):<div className="cm-empty">No patients found.</div>}<footer>Showing {rows.length} of {meta.total||0} patients <div><button disabled={meta.page<=1} onClick={()=>load(meta.page-1)}>‹</button><b>{meta.page||1}</b><button disabled={meta.page>=meta.pages} onClick={()=>load(meta.page+1)}>›</button></div></footer></div>
  {show&&<div className="cm-modal-bg" onMouseDown={()=>setShow(false)}><form className="cm-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={create}><h2>Add Patient</h2>{["name","email","phone","dateOfBirth","gender","emergencyContact","emergencyPhone"].map(k=><label key={k}>{k.replace(/([A-Z])/g," $1")}<input required={k==="name"} type={k==="dateOfBirth"?"date":"text"} value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<div><button type="button" onClick={()=>setShow(false)}>Cancel</button><button className="primary">Add Patient</button></div></form></div>}
 </div>
}