import React,{useEffect,useRef,useState} from 'react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {getMarketplaceUser,marketplaceRequest} from '../../api/marketplaceApi';
import {mountNuveiForm} from './nuveiSdk';
import {QRCodeSVG} from 'qrcode.react';
import {Copy, Check} from 'lucide-react';
import './MarketplaceCheckoutPage.css';
const TITLES={'owner-standard':'Standard','owner-enhanced':'Enhanced Exposure','owner-maximum':'Maximum Exposure','agent-essential':'Essential','agent-growth':'Growth','owner-free-launch':'Free Launch','agent-free-launch':'Free Launch'};
export default function MarketplaceCheckoutPage(){
 const [query]=useSearchParams(),navigate=useNavigate(),user=getMarketplaceUser();
 const [copiedField,setCopiedField]=useState('');
 const planKey=/^(owner|agent)-/.test(query.get('plan')||'')?query.get('plan'):null;
 const [enrollment,setEnrollment]=useState(null),[plans,setPlans]=useState([]),[bank,setBank]=useState(null),[bankReference,setBankReference]=useState('');
 const [status,setStatus]=useState('loading'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[agree,setAgree]=useState(false);
 const [bankTxRef,setBankTxRef]=useState('');const [bankNote,setBankNote]=useState('');
 const [profile,setProfile]=useState({name:'',email:'',phone:''});const gateway=useRef(null),mounted=useRef(false),active=useRef(true);
 const price=enrollment?.price_cents!=null?Number(enrollment.price_cents)/100:plans.find(p=>p.key===planKey)?.priceCents/100;
 const amount=Number.isFinite(price)?`$${price.toFixed(2)}`:'—';
 useEffect(()=>{if(!user){navigate('/marketplace/login?next='+encodeURIComponent('/marketplace/checkout?plan='+encodeURIComponent(planKey||'')),{replace:true});return;}
 setProfile({name:user.fullName||user.full_name||user.name||[user.firstName,user.lastName].filter(Boolean).join(' ')||'',email:user.email||'',phone:user.phone||user.phone_number||''});},[user?.id,navigate,planKey]);
 useEffect(()=>{active.current=true;Promise.all([marketplaceRequest('/marketplace/plans/mine'),marketplaceRequest('/marketplace/plans'),marketplaceRequest('/marketplace/plans/bank-details').catch(()=>null)]).then(([r,p,b])=>{
 if(!active.current)return;setPlans(Array.isArray(p)?p:p.data||[]);setBank(b?.configured?b:null);
 const list=Array.isArray(r.data)?r.data:Array.isArray(r.enrollments)?r.enrollments:[];
 const found=list.find(x=>x.id===sessionStorage.getItem('listoqasa_pending_enrollment')&&x.plan_key===planKey)||list.find(x=>x.plan_key===planKey&&x.status==='pending_payment')||list.find(x=>x.plan_key===planKey&&x.status==='active')||list.find(x=>x.plan_key===planKey);
 if(found){setEnrollment(found);if(String(found.payment_reference||'').startsWith('LQB-'))setBankReference(found.payment_reference);setStatus(found.status);if(found.status==='active')navigate('/create-listing',{replace:true});}else setStatus('not_started');
 }).catch(e=>active.current&&setError(e.message));return()=>{active.current=false};},[planKey,navigate]);
 const check=async(id=enrollment?.id)=>{if(!id)return;const r=await marketplaceRequest('/marketplace/plans/payment/'+encodeURIComponent(id));if(!active.current)return;setStatus(r.status);
 if(r.status==='active'){sessionStorage.removeItem('listoqasa_pending_enrollment');navigate('/create-listing',{replace:true});}
 if(r.status==='failed')setError('Payment was declined. Please contact support before trying again.');};
 useEffect(()=>{if(!enrollment?.id||status!=='pending_payment')return;const t=setInterval(()=>check(enrollment.id).catch(()=>{}),4000);return()=>clearInterval(t);},[enrollment?.id,status]);
 const paymentStarted=!!enrollment?.payment_reference;
 // Informational QR: bank details + amount + reference, NOT a bank-certified payment QR.
 const bankQrText=bank?.configured ? ['LISTOQASA BANK TRANSFER',`Bank: ${bank.bankName||''}`,`Account holder: ${bank.accountHolder||''}`,`Account type: ${bank.accountType||''}`,`Account number: ${bank.accountNumber||''}`,`RUC: ${bank.ruc||''}`,`Amount USD: ${Number.isFinite(price)?price.toFixed(2):''}`,`Reference: ${bankReference||'Generate reference first'}`].join('\n') : ''; 
 useEffect(()=>{if(!user||mounted.current||!enrollment||enrollment.status==='active'||paymentStarted||status==='active')return;
 mounted.current=true;let valid=true;
 marketplaceRequest('/marketplace/plans/payment-config').then(cfg=>{if(!cfg.configured)throw Error('Secure card payment is unavailable.');return mountNuveiForm({containerSelector:'#lq-nuvei-card',environment:cfg.environment,appCode:cfg.clientAppCode,appKey:cfg.clientAppKey,user:{id:user.id,email:user.email},locale:'en',onIncomplete:m=>setError(m||'Complete your card details.')});}).then(async form=>{
 if(!valid)return;gateway.current=form;const ok=await form.ready;if(valid)setReady(ok);if(!ok)throw Error('Secure card form could not be displayed.');form.done.then(card=>{if(valid)charge(card.token)}).catch(e=>{if(valid){setBusy(false);setError(e.message)}});
 }).catch(e=>valid&&setError(e.message));return()=>{valid=false};},[user?.id,enrollment?.id,paymentStarted,status]);
 const charge=async token=>{setBusy(true);setError('');try{let e=enrollment;if(!e){const r=await marketplaceRequest('/marketplace/plans/enroll',{method:'POST',body:JSON.stringify({planKey})});e=r.enrollment;setEnrollment(e);sessionStorage.setItem('listoqasa_pending_enrollment',e.id)}
 if(e.payment_reference)throw Error('Payment already submitted. Awaiting confirmation.');const r=await marketplaceRequest('/marketplace/plans/checkout',{method:'POST',body:JSON.stringify({enrollmentId:e.id,token})});setStatus(r.status);setEnrollment(old=>({...old,...e,payment_reference:r.status==='pending_payment'?'processing':e.payment_reference}));setMessage(r.message||'Waiting for secure payment confirmation.');if(r.status==='active')navigate('/create-listing',{replace:true});else if(r.status==='failed')setError('Payment declined.');}catch(e){setError(e.message)}finally{setBusy(false)}};
 const confirmTransfer=async()=>{if(!enrollment?.id)return;setBusy(true);setError('');try{await marketplaceRequest('/marketplace/plans/bank-confirmation',{method:'POST',body:JSON.stringify({enrollmentId:enrollment.id,bankTransactionReference:bankTxRef,note:bankNote})});navigate('/marketplace/payment-pending?enrollmentId='+encodeURIComponent(enrollment.id));}catch(e){setError(e.message)}finally{setBusy(false)}};
 const pay=()=>{if(!agree){setError('Please accept the Terms and Conditions and Privacy Policy.');return}if(!gateway.current||!ready||busy)return;setError('');setBusy(true);if(!gateway.current.submit()){setBusy(false);setError('Unable to submit the secure card form.')}};
 const copy=async(value,field)=>{if(!value||!navigator.clipboard)return;try{await navigator.clipboard.writeText(String(value));setCopiedField(field)}catch{setError('Could not copy automatically. Please select and copy the value.')}};
 const CopyButton=({value,field,label})=><button type="button" className="lq-copy-button" onClick={()=>copy(value,field)} disabled={!value} aria-label={`Copy ${label}`} title={copiedField===field?'Copied!':`Copy ${label}`}>{copiedField===field?<Check size={15}/>:<Copy size={15}/>}</button>;
 const transfer=async()=>{if(!bank?.configured||!enrollment?.id)return;setBusy(true);setError('');try{const r=await marketplaceRequest('/marketplace/plans/bank-transfer',{method:'POST',body:JSON.stringify({enrollmentId:enrollment.id})});setBankReference(r.reference);setMessage('Transfer reference created. Your plan activates only after the bank transfer is verified.');}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <main className="lq-checkout"><div className="lq-progress" aria-label="Checkout progress"><div className="lq-progress-step done"><span className="lq-progress-mark">✓</span><span className="lq-progress-label">1. Account</span><small>Completed</small></div><i/><div className="lq-progress-step done"><span className="lq-progress-mark">✓</span><span className="lq-progress-label">2. Plan</span><small>Completed</small></div><i/><div className="lq-progress-step current"><span className="lq-progress-mark">3</span><span className="lq-progress-label">Secure Payment</span><small>Your payment details</small></div></div>
 <div className="lq-columns"><div className="lq-left"><section className="lq-panel"><div className="lq-heading"><span className="lq-symbol">♙</span><div><h2>Your information</h2><p>Your marketplace account details.</p></div></div><label>Full Name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} autoComplete="name"/></label><label>Email Address<input value={profile.email} readOnly/></label><label>Phone Number<input value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})} autoComplete="tel"/></label></section>
 <section className="lq-panel lq-plan"><div className="lq-heading"><span className="lq-symbol">▱</span><div><h2>Your selected plan</h2><p>Review your plan details.</p></div><a href={planKey?.startsWith('agent-')?'/agent-plans':'/owner-plans'}>Change plan ↗</a></div><h3>{TITLES[planKey]||planKey||'No plan selected'}</h3><strong>{amount} <small>/ month</small></strong><p>{plans.find(p=>p.key===planKey)?.maxListings==null?'Unlimited active listings':`${plans.find(p=>p.key===planKey)?.maxListings||'—'} active listings`}</p><div className="lq-summary">🏦 <span>Bank transfer</span><b>{amount} today</b></div><div className="lq-summary">▣ <span>Card</span><b>{amount} today</b></div><div className="lq-note">ⓘ Choose your payment method on the right.</div></section></div>
 <div className="lq-right"><section className="lq-panel lq-bank"><div className="lq-heading"><span className="lq-symbol">▤</span><div><h2>1. Bank transfer</h2><p>Pay for your plan by bank transfer.</p></div>{bank?.configured&&<span className="lq-available">Available in Ecuador</span>}</div>{bank?.configured?<><div className="lq-bank-grid"><div><small>Amount to transfer</small><b>{amount}</b><CopyButton value={amount.replace('$','')} field="amount" label="amount"/></div><div><small>Payment reference</small><b>{bankReference||'Generate for your account'}</b><CopyButton value={bankReference} field="reference" label="payment reference"/></div></div><div className="lq-bank-details"><div className="lq-bank-data">{[['Bank',bank.bankName],['Account holder',bank.accountHolder],['Account type',bank.accountType],['Account number',bank.accountNumber],['RUC',bank.ruc]].map(([label,value])=><div key={label}><span>{label}:</span><b>{value||'—'}</b><CopyButton value={value} field={label} label={label}/></div>)}</div><div className="lq-bank-qr"><QRCodeSVG value={bankQrText} size={106} marginSize={1} level="M"/><span>Scan to view transfer details<small>Not an automatic bank payment QR</small></span></div></div><button className="lq-transfer" disabled={busy||!enrollment||!!bankReference} onClick={transfer}>{bankReference?'Transfer reference generated':'Generate bank transfer reference'}</button>{bankReference&&<div className="lq-bank-confirm"><label>Bank transaction reference<input value={bankTxRef} maxLength={120} onChange={e=>setBankTxRef(e.target.value)} /></label><label>Transfer note (optional)<input value={bankNote} maxLength={1000} onChange={e=>setBankNote(e.target.value)} /></label><button className="lq-transfer" disabled={busy||bankTxRef.trim().length<4} onClick={confirmTransfer}>Submit transfer confirmation</button></div>}<small className="lq-footnote">Your plan activates only after an admin verifies the received funds.</small></>:<div className="lq-bank-unavailable">Bank transfer is not available until verified bank details are configured.</div>}</section>
 <div className="lq-or">OR</div><section className="lq-panel lq-card"><div className="lq-heading"><span className="lq-symbol">▣</span><div><h2>2. Credit or debit card</h2><p>Pay securely for your plan.</p></div><span className="lq-cards">VISA　●●</span></div>
 {paymentStarted?<div className="lq-wait">Payment is being verified. This page will continue automatically when confirmed.</div>:<div id="lq-nuvei-card" className="lq-card-frame" aria-label="Nuvei secure card fields"/>}
 {!paymentStarted&&<><label className="lq-consent"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/><span>I accept the <a href="/terms" target="_blank" rel="noreferrer">Terms and Conditions</a> and <a href="/privacy" target="_blank" rel="noreferrer">Privacy Policy</a>.</span></label><button className="lq-pay" disabled={!agree||!ready||busy||!enrollment} onClick={pay}>♙ {busy?'Processing…':`Pay ${amount} and continue`}</button></>}
 <div className="lq-security">♢ Secure tokenization　　♙ 3DS protection</div><small className="lq-footnote">Secure payments processed by Nuvei / Datafast.</small></section></div></div>
 {message&&<p className="lq-feedback" role="status">{message}</p>}{error&&<p className="lq-feedback error" role="alert">{error}</p>}
 {enrollment&&<button className="lq-refresh" onClick={()=>check().catch(e=>setError(e.message))}>Refresh payment status</button>}</main>;
}
