import React,{useEffect,useMemo,useState} from "react";
import {Search,Bell,ChevronDown,TrendingUp,AlertTriangle,UserRound,ChevronLeft,ChevronRight,Filter,X,CheckCircle2,RefreshCw,CalendarClock,Send,Download,Info,RotateCw,CircleDollarSign,WalletCards} from "lucide-react";
import {ecommerceBillingApi} from "./ecommerceBillingApi";
import "./ecommerce-dashboard.css";
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(n||0));
const ymd=d=>new Date(d).toISOString().slice(0,10); const ym=d=>ymd(d).slice(0,7);
function MetricCard({label,value,Icon,tone}){return <article className="ecbd-metric"><div><span>{label}</span><strong>{value}</strong><small>No placeholder data</small></div><b className={`ecbd-metric-icon ${tone}`}><Icon/></b></article>}
function Empty({children="No records for this workspace."}){return <p className="ecbd-empty"><Info/>{children}</p>}
export default function EcommerceDashboard(){
 const [cursor,setCursor]=useState(new Date()),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""); const [selected,setSelected]=useState(ymd(new Date())),[day,setDay]=useState({data:[],stats:{},total:0}),[filter,setFilter]=useState("all"),[search,setSearch]=useState(""),[checked,setChecked]=useState([]),[busy,setBusy]=useState("");
 const load=async()=>{setLoading(true);try{setData(await ecommerceBillingApi.dashboard(ym(cursor)));setError("")}catch(e){setError(e.message)}finally{setLoading(false)}}; useEffect(()=>{load()},[cursor]);
 const loadDay=async()=>{try{setDay(await ecommerceBillingApi.day(selected,{status:filter,search,page:1,limit:50}));setChecked([])}catch(e){setError(e.message)}}; useEffect(()=>{loadDay()},[selected,filter,search]);
 const days=useMemo(()=>Object.fromEntries((data?.calendar||[]).map(x=>[Number(x.day),x])),[data]); const year=cursor.getFullYear(),month=cursor.getMonth(),count=new Date(year,month+1,0).getDate(),offset=new Date(year,month,1).getDay(); const cells=[...Array(offset).fill(null),...Array.from({length:count},(_,i)=>i+1)];
 const act=async(fn)=>{setBusy(fn);try{if(fn==="reminder"){for(const id of checked)await ecommerceBillingApi.reminder(id);}else if(fn==="reschedule"){const date=window.prompt("New billing date (YYYY-MM-DD)");if(!date)return;await ecommerceBillingApi.bulkReschedule({subscriptionIds:checked,date});}await Promise.all([load(),loadDay()]);}catch(e){setError(e.message)}finally{setBusy("")}};
 const exportCsv=()=>{const rows=day.data||[];const q=v=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[["Customer","Email","Plan","Amount","Billing Date","Status","Provider"],...rows.map(r=>[r.customer_name,r.email,r.plan,r.amount,r.current_period_end,r.status,r.provider])].map(r=>r.map(q).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`billing-${selected}.csv`;a.click();URL.revokeObjectURL(a.href)};
 const caps=data?.capabilities||{}; const provider=data?.provider||{}; const m=data?.metrics||{}; const account=data?.account||{};
 return <div className="ecbd-page"><header className="ecbd-topbar"><div><h1>Dashboard Billing Calendar</h1><p>Real subscription charges, payments, failures, and billing activity for this workspace.</p></div><div className="ecbd-user-tools"><span className="ecbd-avatar">{(account.name||account.email||"A")[0]?.toUpperCase()}</span><b>{account.name||account.email||"Account"}<small>{account.role||"Workspace user"}</small></b><ChevronDown/></div></header>
 <div className="ecbd-content">{error&&<div className="ecbd-api-error"><AlertTriangle/>{error}</div>}{loading&&!data?<Empty>Loading billing data…</Empty>:<><div className="ecbd-metrics"><MetricCard label="Monthly Revenue" value={money(m.monthlyRevenue)} Icon={CircleDollarSign} tone="purple"/><MetricCard label="Active Subscriptions" value={m.activeSubscriptions||0} Icon={WalletCards} tone="green"/><MetricCard label="MRR Forecast (30 Days)" value={money(m.mrrForecast)} Icon={TrendingUp} tone="blue"/><MetricCard label="Failed Payments" value={m.failedPayments||0} Icon={AlertTriangle} tone="orange"/><MetricCard label="Churn Rate" value={`${Number(m.churnRate||0).toFixed(2)}%`} Icon={UserRound} tone="violet"/></div>
 <div className="ecbd-main-grid"><section className="ecbd-card ecbd-calendar-card"><header className="ecbd-card-head"><h2>Billing Calendar</h2></header><div className="ecbd-calendar-nav"><button onClick={()=>{const n=new Date();setCursor(n);setSelected(ymd(n))}}>Today</button><button onClick={()=>setCursor(new Date(year,month-1,1))}><ChevronLeft/></button><button onClick={()=>setCursor(new Date(year,month+1,1))}><ChevronRight/></button><strong>{cursor.toLocaleString("en-US",{month:"long",year:"numeric"})}</strong></div><div className="ecbd-weekdays">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><b key={x}>{x}</b>)}</div><div className="ecbd-month-grid">{cells.map((d,i)=>d?<button key={d} className={selected===ymd(new Date(year,month,d))?"selected":""} onClick={()=>setSelected(ymd(new Date(year,month,d)))}><div><b>{d}</b><i>{days[d]?.count||0}</i></div><strong>{money(days[d]?.amount||0)}</strong></button>:<button className="outside" key={`e${i}`} disabled/> )}</div></section>
 <section className="ecbd-card ecbd-day-card"><header className="ecbd-card-head"><h2>{new Date(`${selected}T12:00:00`).toLocaleDateString("en-US",{weekday:"long",year:"numeric",month:"long",day:"numeric"})}</h2><button className="ecbd-close" onClick={()=>setChecked([])}><X/>Clear</button></header><div className="ecbd-day-stats">{[["Scheduled",day.stats?.scheduled||0],["Paid",day.stats?.paid||0],["Failed",day.stats?.failed||0],["Past Due",day.stats?.past_due||0]].map(([s,n])=><button key={s} onClick={()=>setFilter(s==="Scheduled"?"all":String(s).toLowerCase().replace(" ","_"))}><strong>{n}</strong><span>{s}</span></button>)}</div><div className="ecbd-search-row"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customers..."/></label></div><div className="ecbd-customer-table"><div className="ecbd-tr ecbd-th"><span>Customer</span><span>Plan</span><span>Billing Time</span><span>Status</span><span>Actions</span></div>{day.data?.map(r=><div className="ecbd-tr" key={r.id}><span className="ecbd-customer"><input type="checkbox" checked={checked.includes(r.id)} onChange={()=>setChecked(x=>x.includes(r.id)?x.filter(v=>v!==r.id):[...x,r.id])}/><b>{r.customer_name||r.email||"Customer"}<small>{r.email||""}</small></b></span><span><b>{r.plan}</b><small>{money(r.amount)}</small></span><span>{r.current_period_end?new Date(r.current_period_end).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—"}</span><span><em className={String(r.status).replaceAll("_","").toLowerCase()}>{r.status}</em></span><span>{r.provider||"—"}</span></div>)}{!day.data?.length&&<Empty>No billing records for this date.</Empty>}</div><footer className="ecbd-pagination"><span>Showing {day.data?.length||0} of {day.total||0} customers</span></footer></section></div>
 <div className="ecbd-bottom-grid"><section className="ecbd-card ecbd-mini"><header><h3>Upcoming Billing Days</h3></header>{data?.upcoming?.map((x,i)=><p key={i}><b>{new Date(x.day).toLocaleDateString()}</b><span>{x.count} customers</span><strong>{money(x.amount)}</strong></p>)}{!data?.upcoming?.length&&<Empty/>}</section><section className="ecbd-card ecbd-mini"><header><h3>Recent Activity</h3></header>{data?.activity?.map(x=><p className="activity" key={x.id}><CheckCircle2/><b>{String(x.status).replaceAll("_"," ")}<small>{x.name||x.email||"Customer"}</small></b><span>{x.payment_date?new Date(x.payment_date).toLocaleString():"—"}</span><strong>{money(x.amount)}</strong></p>)}{!data?.activity?.length&&<Empty>No billing activity yet.</Empty>}</section><section className="ecbd-card ecbd-mini ecbd-exceptions"><header><h3>Billing Exceptions</h3><button disabled={!caps.recoveryRules} title={caps.recoveryRulesReason||""}>Recovery Rules</button></header><p><b>Failed Payments</b><span>{data?.exceptions?.failed||0}</span></p><p><b>Past Due</b><span>{data?.exceptions?.past_due||0}</span></p><p><b>Refunded</b><span>{data?.exceptions?.refunded||0}</span></p></section><section className="ecbd-card ecbd-bulk"><h3>Bulk Actions <small>({checked.length} selected)</small></h3><div className="ecbd-actions"><button disabled={!checked.length||!caps.reschedule||!!busy} onClick={()=>act("reschedule")}><CalendarClock/>Reschedule</button><button disabled={!checked.length||!caps.sendReminder||!!busy} onClick={()=>act("reminder")}><Send/>Send Reminder</button><button disabled={!checked.length||!caps.retryFailed} title={caps.retryFailedReason||""}><RefreshCw/>Retry Failed</button><button disabled={!caps.export} onClick={exportCsv}><Download/>Export List</button></div><hr/><h3>Quick Reschedule</h3><div className="ecbd-quick"><span>Move selected to</span><button disabled={!checked.length||!caps.quickReschedule} onClick={()=>act("reschedule")}>Choose date</button></div>{!caps.retryFailed&&<p><Info/>{caps.retryFailedReason}</p>}{!caps.recoveryRules&&<p><Info/>{caps.recoveryRulesReason}</p>}</section></div><div className="ecbd-statusbar"><span><Info/>Billing data is scoped to the signed-in workspace.</span><span><b>Provider:</b><i/>{provider.name?`${provider.name} · ${provider.status}`:"Not connected"}<em/>Last sync: {provider.lastSyncAt?new Date(provider.lastSyncAt).toLocaleString():"—"}<button onClick={load}><RotateCw/></button></span></div></>}</div></div>;
}
