import React, { useEffect, useMemo, useState } from "react";
import {
  Search, Bell, ChevronDown, TrendingUp, TrendingDown, AlertTriangle,
  UserRound, ChevronLeft, ChevronRight, Filter, X, MoreHorizontal,
  CheckCircle2, RefreshCw, CalendarClock, Send, Download, Info,
  RotateCw, CircleDollarSign, WalletCards
} from "lucide-react";
import "./ecommerce-dashboard.css";
import EcommerceAccountMenu from "./EcommerceAccountMenu";
import { useEcommercePageLanguage, ecT } from "./EcommerceLocale";
import { ecommerceBillingApi } from "./ecommerceBillingApi";

const EMPTY_METRICS = [
  ["Monthly Revenue", 0, null, "flat", CircleDollarSign, "purple", "currency"],
  ["Active Subscriptions", 0, null, "flat", WalletCards, "green", "number"],
  ["MRR Forecast (30 Days)", 0, null, "flat", TrendingUp, "blue", "currency"],
  ["Failed Payments", 0, null, "flat", AlertTriangle, "orange", "number"],
  ["Churn Rate", 0, null, "flat", UserRound, "violet", "percent"],
];
const STATUS_ORDER=["Scheduled","Paid","Failed","Past Due"];
const n=v=>Number(v??0)||0;
const money=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2}).format(n(v));
const num=v=>new Intl.NumberFormat("en-US").format(n(v));
const dateKey=d=>{const x=new Date(d);return Number.isNaN(x.getTime())?String(d||"").slice(0,10):`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`};
const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;
const get=(o,...keys)=>{for(const k of keys){if(o&&o[k]!==undefined&&o[k]!==null)return o[k]}return undefined};

function normalizeDashboard(raw={}){
  const d=raw?.data||raw||{}; const m=d.metrics||d.summary||d.stats||{};
  const metrics=[
    ["Monthly Revenue",get(m,"monthlyRevenue","monthly_revenue","revenue")],
    ["Active Subscriptions",get(m,"activeSubscriptions","active_subscriptions","active")],
    ["MRR Forecast (30 Days)",get(m,"mrrForecast","mrr_forecast","forecast30Days","forecast")],
    ["Failed Payments",get(m,"failedPayments","failed_payments","failed")],
    ["Churn Rate",get(m,"churnRate","churn_rate","churn")],
  ].map((x,i)=>{
    const base=EMPTY_METRICS[i]; const change=get(m,`${["monthlyRevenue","activeSubscriptions","mrrForecast","failedPayments","churnRate"][i]}Change`,`${["monthly_revenue","active_subscriptions","mrr_forecast","failed_payments","churn_rate"][i]}_change`);
    return [base[0],n(x[1]),change==null?null:n(change),n(change)<0?"down":n(change)>0?"up":"flat",base[4],base[5],base[6]];
  });
  const days=(d.billingDays||d.calendar||d.days||[]).map(x=>({date:dateKey(get(x,"date","billingDate","billing_date")),day:n(get(x,"day","dayOfMonth"))||Number(String(get(x,"date","billingDate","billing_date")||"").slice(8,10)),count:n(get(x,"count","customers","customerCount","subscriptionCount")),amount:n(get(x,"amount","total","totalAmount","revenue")),statuses:get(x,"statuses","statusCounts")||{}}));
  return {metrics,days,upcoming:d.upcomingBillingDays||d.upcoming||[],activity:d.recentActivity||d.activity||[],exceptions:d.billingExceptions||d.exceptions||[],provider:d.providerStatus||d.paymentProvider||d.gatewayStatus||null,selectedDate:get(d,"selectedDate","selected_date")};
}
function normalizeDay(raw={}){const d=raw?.data||raw||{};const s=d.stats||d.summary||{};return {stats:STATUS_ORDER.map(status=>{const k=status.replace(/ /g,"").replace(/^./,c=>c.toLowerCase());const v=s[k]||s[status]||{};return {status,count:n(get(v,"count","customers")??v),amount:n(get(v,"amount","total"))}}),customers:d.customers||d.items||d.rows||[],total:n(get(d,"total","totalCustomers","count")),page:n(d.page)||1,totalPages:n(get(d,"totalPages","pages"))||1};}

function MetricCard({ item }) {const [label,value,change,direction,Icon,tone,type]=item;const shown=type==="currency"?money(value):type==="percent"?`${n(value).toFixed(2)}%`:num(value);return <article className="ecbd-metric"><div><span>{ecT(label)}</span><strong>{shown}</strong>{change!=null&&<small className={direction}>{direction==="down"?<TrendingDown/>:direction==="up"?<TrendingUp/>:null}{Math.abs(change).toFixed(1)}% <i>vs last month</i></small>}</div><b className={`ecbd-metric-icon ${tone}`}><Icon/></b></article>}
function StatusDots(){return <span className="ecbd-dots"><i/><i/><i/><i/><i/></span>}

function BillingCalendar({month,setMonth,days,selectedDate,onSelect}){const [view,setView]=useState("Month");const first=new Date(`${month}-01T00:00:00`);const lead=first.getDay();const count=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();const prevCount=new Date(first.getFullYear(),first.getMonth(),0).getDate();const map=new Map(days.map(x=>[x.date,x]));const cells=[];for(let i=lead-1;i>=0;i--)cells.push({outside:true,day:prevCount-i});for(let day=1;day<=count;day++){const key=`${month}-${String(day).padStart(2,"0")}`;cells.push({day,key,data:map.get(key)});}while(cells.length%7)cells.push({outside:true,day:cells.length-count-lead+1});const move=delta=>{const x=new Date(first);x.setMonth(x.getMonth()+delta);setMonth(monthKey(x))};return <section className="ecbd-card ecbd-calendar-card"><header className="ecbd-card-head"><h2>{ecT("Billing Calendar")}</h2><div className="ecbd-view-toggle">{["Month","Week","List"].map(v=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}>{ecT(v)}</button>)}<button aria-label="Filter"><Filter/></button></div></header><div className="ecbd-calendar-nav"><button onClick={()=>setMonth(monthKey(new Date()))}>{ecT("Today")}</button><button onClick={()=>move(-1)}><ChevronLeft/></button><button onClick={()=>move(1)}><ChevronRight/></button><strong>{first.toLocaleDateString(undefined,{month:"long",year:"numeric"})} <ChevronDown/></strong></div><div className="ecbd-legend">{["Scheduled","Paid","Failed","Past Due","Canceled","Rescheduled"].map(x=><span key={x}>{ecT(x)}</span>)}</div><div className="ecbd-weekdays">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><b key={x}>{x}</b>)}</div><div className="ecbd-month-grid">{cells.map((c,i)=>c.outside?<button className="outside" key={`o-${i}`}>{c.day}</button>:<button key={c.key} className={selectedDate===c.key?"selected":""} onClick={()=>onSelect(c.key)}><div><b>{c.day}</b>{c.data&&<i>{num(c.data.count)}</i>}</div>{c.data&&<><strong>{money(c.data.amount)}</strong><StatusDots/></>}</button>)}</div></section>}

function SelectedDay({date,data,loading}){const [filter,setFilter]=useState("All");const customers=data.customers||[];const rows=useMemo(()=>customers.filter(r=>filter==="All"||String(get(r,"status","paymentStatus","payment_status")||"").toLowerCase()===filter.toLowerCase()),[customers,filter]);const title=date?new Date(`${date}T00:00:00`).toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"}):"—";return <section className="ecbd-card ecbd-day-card"><header className="ecbd-card-head"><h2>{title}</h2><button className="ecbd-close"><X/>Close</button></header><div className="ecbd-day-stats">{data.stats.map(x=><button key={x.status} className={filter===x.status?"active":""} onClick={()=>setFilter(filter===x.status?"All":x.status)}><strong>{num(x.count)}</strong><span>{ecT(x.status)}</span><b>{money(x.amount)}</b></button>)}</div><div className="ecbd-search-row"><label><Search/><input placeholder={ecT("Search customers...")}/></label><button><Filter/>{ecT("Filters")}</button></div><div className="ecbd-customer-table"><div className="ecbd-tr ecbd-th"><span>{ecT("Customer")}</span><span>{ecT("Plan")}</span><span>{ecT("Billing Time")}</span><span>{ecT("Status")}</span><span>{ecT("Actions")}</span></div>{!loading&&rows.map((r,i)=>{const name=get(r,"name","customerName","customer_name","email")||"—";const initials=name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();const status=get(r,"status","paymentStatus","payment_status")||"Scheduled";return <div className="ecbd-tr" key={get(r,"id","customerId","customer_id")||i}><span className="ecbd-customer"><i>{initials}</i><b>{name}<small>{get(r,"email","customerEmail","customer_email")||""}</small></b></span><span><b>{get(r,"plan","planName","plan_name")||"—"}</b><small>{get(r,"price","planPrice","plan_price")||""}</small></span><span>{get(r,"billingTime","billing_time")||"—"}</span><span><em className={String(status).replaceAll(" ","").toLowerCase()}>{ecT(status)}</em></span><span><button className="ecbd-more"><MoreHorizontal/></button></span></div>})}</div>{!loading&&rows.length===0&&<div className="ecbd-empty">No customers scheduled for this date.</div>}<footer className="ecbd-pagination"><span>{data.total?`Showing ${rows.length} of ${data.total} customers`:"0 customers"}</span></footer></section>}

function BottomPanels({dashboard}){const upcoming=dashboard.upcoming||[],activity=dashboard.activity||[],exceptions=dashboard.exceptions||[];return <div className="ecbd-bottom-grid"><section className="ecbd-card ecbd-mini"><header><h3>{ecT("Upcoming Billing Days")}</h3><a>{ecT("View all →")}</a></header>{upcoming.length?upcoming.map((x,i)=><p key={i}><b>{get(x,"label","date")||"—"}</b><span>{num(get(x,"customers","count"))} customers</span><strong>{money(get(x,"amount","total"))}</strong></p>):<div className="ecbd-empty">No upcoming billing days.</div>}</section><section className="ecbd-card ecbd-mini"><header><h3>{ecT("Recent Activity")}</h3><a>{ecT("View all →")}</a></header>{activity.length?activity.map((x,i)=><p className="activity" key={i}><CheckCircle2/><b>{get(x,"title","type")||"—"}<small>{get(x,"customer","customerName","description")||""}</small></b><span>{get(x,"time","createdAt","created_at")||""}</span><strong>{get(x,"amount","value")??""}</strong></p>):<div className="ecbd-empty">No recent billing activity.</div>}</section><section className="ecbd-card ecbd-mini ecbd-exceptions"><header><h3>{ecT("Billing Exceptions")}</h3><button>{ecT("Recovery Rules")}</button><a>{ecT("View all →")}</a></header>{exceptions.length?exceptions.map((x,i)=><p key={i}><b>{get(x,"label","type")||"—"}</b><span>{num(get(x,"customers","count"))} customers</span></p>):<div className="ecbd-empty">No billing exceptions.</div>}</section><section className="ecbd-card ecbd-bulk"><h3>{ecT("Bulk Actions")} <small>(0 selected)</small></h3><div className="ecbd-actions"><button disabled><CalendarClock/>{ecT("Reschedule")}</button><button disabled><Send/>{ecT("Send Reminder")}</button><button disabled><RefreshCw/>{ecT("Retry Failed")}</button><button disabled><Download/>{ecT("Export List")}</button></div><hr/><h3>{ecT("Quick Reschedule")}</h3><div className="ecbd-quick"><span>Move selected to</span><button disabled>—</button><button className="purple" disabled>{ecT("Reschedule")}</button></div><p><Info/>Billing actions become available after selecting real workspace subscriptions.</p></section></div>}

export default function EcommerceDashboard(){useEcommercePageLanguage();const [month,setMonth]=useState(monthKey(new Date()));const [dashboard,setDashboard]=useState(()=>normalizeDashboard());const [selectedDate,setSelectedDate]=useState(`${month}-01`);const [day,setDay]=useState(()=>normalizeDay());const [loading,setLoading]=useState(true);const [dayLoading,setDayLoading]=useState(false);const [error,setError]=useState("");
useEffect(()=>{let live=true;setLoading(true);setError("");ecommerceBillingApi.dashboard(month).then(r=>{if(!live)return;const d=normalizeDashboard(r);setDashboard(d);const candidate=d.selectedDate?dateKey(d.selectedDate):(d.days[0]?.date||`${month}-01`);setSelectedDate(candidate)}).catch(e=>{if(live){setDashboard(normalizeDashboard());setError(e.message||"Billing data is unavailable.")}}).finally(()=>live&&setLoading(false));return()=>{live=false}},[month]);
useEffect(()=>{if(!selectedDate)return;let live=true;setDayLoading(true);ecommerceBillingApi.day(selectedDate).then(r=>live&&setDay(normalizeDay(r))).catch(()=>live&&setDay(normalizeDay())).finally(()=>live&&setDayLoading(false));return()=>{live=false}},[selectedDate]);
return <div className="ecbd-page"><header className="ecbd-topbar"><div><h1>{ecT("Dashboard Billing Calendar")}</h1><p>{ecT("Monitor upcoming subscription charges, payments, failures, and billing activity.")}</p></div><div className="ecbd-user-tools"><label><Search/><input placeholder={ecT("Search customers, invoices...")}/><kbd>⌘K</kbd></label><button className="ecbd-bell"><Bell/></button><EcommerceAccountMenu/></div></header><div className="ecbd-content">{error&&<div className="ecbd-api-warning"><AlertTriangle/> {error}</div>}<div className="ecbd-metrics">{dashboard.metrics.map((m,i)=><MetricCard key={i} item={m}/>)}</div><div className="ecbd-main-grid"><BillingCalendar month={month} setMonth={setMonth} days={dashboard.days} selectedDate={selectedDate} onSelect={setSelectedDate}/><SelectedDay date={selectedDate} data={day} loading={dayLoading}/></div><BottomPanels dashboard={dashboard}/><div className="ecbd-statusbar"><span><Info/>Cortexa manages billing schedules. Payment results are synchronized from the connected payment provider.</span><span><b>Payment Provider:</b>{dashboard.provider?String(get(dashboard.provider,"status","name")||"Connected"):"—"} <button onClick={()=>setMonth(x=>x)}><RotateCw/></button></span></div></div></div>}
