import {useEffect,useState} from "react";

export const EC_LANG_KEY="cortexa_ecommerce_language";
export const EC_LANGS={en:"EN",es:"ES",pt:"PT"};
export const EC_LANG_EVENT="cortexa:ecommerce-language-change";
export function getEcommerceLanguage(){const x=(localStorage.getItem(EC_LANG_KEY)||localStorage.getItem("i18nextLng")||"en").slice(0,2);return EC_LANGS[x]?x:"en"}
export function ecT(text,lang=getEcommerceLanguage()){if(lang==="en")return text;const dict=lang==="es"?ES:PT;return dict[text]||text}

const ES={
"Dashboard Billing Calendar":"Calendario de facturación","Monitor upcoming subscription charges, payments, failures, and billing activity.":"Supervisa próximos cargos, pagos, fallos y actividad de facturación.","Monthly Revenue":"Ingresos mensuales","Active Subscriptions":"Suscripciones activas","MRR Forecast (30 Days)":"Pronóstico MRR (30 días)","Failed Payments":"Pagos fallidos","Churn Rate":"Tasa de cancelación","Billing Calendar":"Calendario de facturación","Month":"Mes","Week":"Semana","List":"Lista","Today":"Hoy","Scheduled":"Programado","Paid":"Pagado","Failed":"Fallido","Past Due":"Vencido","Canceled":"Cancelado","Rescheduled":"Reprogramado","Customer":"Cliente","Plan":"Plan","Billing Time":"Hora de cobro","Status":"Estado","Actions":"Acciones","Filters":"Filtros","Upcoming Billing Days":"Próximos días de cobro","Recent Activity":"Actividad reciente","Billing Exceptions":"Excepciones de facturación","Bulk Actions":"Acciones masivas","Recovery Rules":"Reglas de recuperación","Reschedule":"Reprogramar","Send Reminder":"Enviar recordatorio","Retry Failed":"Reintentar fallidos","Export List":"Exportar lista","Quick Reschedule":"Reprogramación rápida","View all →":"Ver todo →","Search customers...":"Buscar clientes...","Search customers, invoices...":"Buscar clientes, facturas...",
"Subscriptions":"Suscripciones","All registered accounts, subscriptions, and plans — everything in one place.":"Todas las cuentas, suscripciones y planes registrados, todo en un solo lugar.","Export CSV":"Exportar CSV","Import Customers":"Importar clientes","Add Customer":"Añadir cliente","Total Registered":"Total registrados","Active Customers":"Clientes activos","MRR (Monthly Recurring)":"MRR (recurrente mensual)","ARR (Annual Recurring)":"ARR (recurrente anual)","Conversion Rate":"Tasa de conversión","Free Accounts":"Cuentas gratuitas","Customers by Plan":"Clientes por plan","Customer Status":"Estado del cliente","Customer Activity":"Actividad del cliente","Workspace Opportunity":"Oportunidad de workspace","All Subscriptions":"Todas las suscripciones","Registered (Sign-ups)":"Registrados","Free":"Gratis","Trialing":"En prueba","Active Paid":"Activos de pago","All Plans":"Todos los planes","All Cycles":"Todos los ciclos","All Statuses":"Todos los estados","All Sources":"Todas las fuentes","All Languages":"Todos los idiomas","All Countries":"Todos los países","Users & Seats":"Usuarios y plazas","More Filters":"Más filtros","Clear Filters":"Limpiar filtros","Change Plan":"Cambiar plan","Update Payment":"Actualizar pago","Add Seat / User":"Añadir plaza / usuario","Send Email":"Enviar email","Export":"Exportar","More":"Más","No customers match these filters.":"Ningún cliente coincide con estos filtros.","No subscriptions":"Sin suscripciones","Rows per page:":"Filas por página:","Search by name, email or company":"Buscar por nombre, email o empresa",
"Integrations":"Integraciones","Connect and manage your critical business services and API integrations.":"Conecta y administra tus servicios empresariales e integraciones API.","Add Integration":"Añadir integración","Connected Integrations":"Integraciones conectadas","Healthy Connections":"Conexiones saludables","Syncs (30d)":"Sincronizaciones (30d)","Failed Syncs (30d)":"Sincronizaciones fallidas (30d)","Last Sync":"Última sincronización","Current account":"Cuenta actual","Current status":"Estado actual","Last 30 days":"Últimos 30 días","All systems status":"Estado de todos los sistemas","All Categories":"Todas las categorías","Connected":"Conectadas","Needs Attention":"Requiere atención","Popular":"Populares","Recently Added":"Añadidas recientemente","All Integrations":"Todas las integraciones","Search integrations...":"Buscar integraciones...","Integration Health":"Salud de integraciones","Healthy":"Saludables","Warning":"Advertencia","Error":"Error","Not Connected":"No conectadas","Total":"Total","View Health Details":"Ver detalles de salud","Recent Integration Events":"Eventos recientes de integración","Need Help?":"¿Necesitas ayuda?","Explore our integration guides or contact our support team.":"Explora nuestras guías de integración o contacta con soporte.","Integration Guides":"Guías de integración","API Documentation":"Documentación API","Contact Support":"Contactar soporte","Popular Integrations":"Integraciones populares","No popular integrations available.":"No hay integraciones populares disponibles.","Recently Connected Integrations":"Integraciones conectadas recientemente","No integrations connected yet.":"Aún no hay integraciones conectadas.","No recent integration events.":"No hay eventos recientes de integración.","Dashboard":"Panel","Log out":"Cerrar sesión","Log Out":"Cerrar sesión"
};
const PT={
"Dashboard Billing Calendar":"Calendário de faturamento","Monitor upcoming subscription charges, payments, failures, and billing activity.":"Monitore próximas cobranças, pagamentos, falhas e atividades de faturamento.","Monthly Revenue":"Receita mensal","Active Subscriptions":"Assinaturas ativas","MRR Forecast (30 Days)":"Previsão de MRR (30 dias)","Failed Payments":"Pagamentos falhados","Churn Rate":"Taxa de cancelamento","Billing Calendar":"Calendário de faturamento","Month":"Mês","Week":"Semana","List":"Lista","Today":"Hoje","Scheduled":"Agendado","Paid":"Pago","Failed":"Falhou","Past Due":"Em atraso","Canceled":"Cancelado","Rescheduled":"Reagendado","Customer":"Cliente","Plan":"Plano","Billing Time":"Hora da cobrança","Status":"Status","Actions":"Ações","Filters":"Filtros","Upcoming Billing Days":"Próximos dias de cobrança","Recent Activity":"Atividade recente","Billing Exceptions":"Exceções de faturamento","Bulk Actions":"Ações em massa","Recovery Rules":"Regras de recuperação","Reschedule":"Reagendar","Send Reminder":"Enviar lembrete","Retry Failed":"Tentar falhas novamente","Export List":"Exportar lista","Quick Reschedule":"Reagendamento rápido","View all →":"Ver tudo →","Search customers...":"Buscar clientes...","Search customers, invoices...":"Buscar clientes, faturas...",
"Subscriptions":"Assinaturas","All registered accounts, subscriptions, and plans — everything in one place.":"Todas as contas, assinaturas e planos registrados em um só lugar.","Export CSV":"Exportar CSV","Import Customers":"Importar clientes","Add Customer":"Adicionar cliente","Total Registered":"Total registrados","Active Customers":"Clientes ativos","MRR (Monthly Recurring)":"MRR (recorrente mensal)","ARR (Annual Recurring)":"ARR (recorrente anual)","Conversion Rate":"Taxa de conversão","Free Accounts":"Contas gratuitas","Customers by Plan":"Clientes por plano","Customer Status":"Status do cliente","Customer Activity":"Atividade do cliente","Workspace Opportunity":"Oportunidade de workspace","All Subscriptions":"Todas as assinaturas","Registered (Sign-ups)":"Registrados","Free":"Grátis","Trialing":"Em teste","Active Paid":"Pagos ativos","All Plans":"Todos os planos","All Cycles":"Todos os ciclos","All Statuses":"Todos os status","All Sources":"Todas as fontes","All Languages":"Todos os idiomas","All Countries":"Todos os países","Users & Seats":"Usuários e assentos","More Filters":"Mais filtros","Clear Filters":"Limpar filtros","Change Plan":"Alterar plano","Update Payment":"Atualizar pagamento","Add Seat / User":"Adicionar assento / usuário","Send Email":"Enviar email","Export":"Exportar","More":"Mais","No customers match these filters.":"Nenhum cliente corresponde a estes filtros.","No subscriptions":"Sem assinaturas","Rows per page:":"Linhas por página:","Search by name, email or company":"Buscar por nome, email ou empresa",
"Integrations":"Integrações","Connect and manage your critical business services and API integrations.":"Conecte e gerencie seus serviços empresariais e integrações de API.","Add Integration":"Adicionar integração","Connected Integrations":"Integrações conectadas","Healthy Connections":"Conexões saudáveis","Syncs (30d)":"Sincronizações (30d)","Failed Syncs (30d)":"Sincronizações falhadas (30d)","Last Sync":"Última sincronização","Current account":"Conta atual","Current status":"Status atual","Last 30 days":"Últimos 30 dias","All systems status":"Status de todos os sistemas","All Categories":"Todas as categorias","Connected":"Conectadas","Needs Attention":"Requer atenção","Popular":"Populares","Recently Added":"Adicionadas recentemente","All Integrations":"Todas as integrações","Search integrations...":"Buscar integrações...","Integration Health":"Saúde das integrações","Healthy":"Saudáveis","Warning":"Aviso","Error":"Erro","Not Connected":"Não conectadas","Total":"Total","View Health Details":"Ver detalhes de saúde","Recent Integration Events":"Eventos recentes de integração","Need Help?":"Precisa de ajuda?","Explore our integration guides or contact our support team.":"Explore nossos guias de integração ou entre em contato com o suporte.","Integration Guides":"Guias de integração","API Documentation":"Documentação da API","Contact Support":"Contatar suporte","Popular Integrations":"Integrações populares","No popular integrations available.":"Nenhuma integração popular disponível.","Recently Connected Integrations":"Integrações conectadas recentemente","No integrations connected yet.":"Ainda não há integrações conectadas.","No recent integration events.":"Nenhum evento recente de integração.","Dashboard":"Painel","Log out":"Sair","Log Out":"Sair"
};
function translateDynamic(s,dict){
 if(dict[s]) return dict[s];
 let m=s.match(/^(\d+) Healthy$/); if(m&&dict.Healthy)return `${m[1]} ${dict.Healthy}`;
 m=s.match(/^(\d+) Warning$/); if(m&&dict.Warning)return `${m[1]} ${dict.Warning}`;
 m=s.match(/^(\d+) Error$/); if(m&&dict.Error)return `${m[1]} ${dict.Error}`;
 m=s.match(/^(\d+) Not Connected$/); if(m&&dict["Not Connected"])return `${m[1]} ${dict["Not Connected"]}`;
 return s;
}
export function applyEcommerceLanguage(lang){
 document.documentElement.lang=lang;
 if(lang==="en")return;
 const dict=lang==="es"?ES:PT;
 const root=document.querySelector(".ecbd-page,.ecs-page,.eci-page"); if(!root)return;
 const walk=()=>{
  const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); let n;
  while((n=w.nextNode())){const raw=n.nodeValue;const s=raw.trim();if(!s)continue;const tr=translateDynamic(s,dict);if(tr!==s)n.nodeValue=raw.replace(s,tr)}
  root.querySelectorAll("input[placeholder]").forEach(el=>{const s=el.getAttribute("placeholder");if(dict[s])el.setAttribute("placeholder",dict[s])});
  root.querySelectorAll("option").forEach(el=>{const s=el.textContent.trim();if(dict[s])el.textContent=dict[s]});
 };
 walk(); setTimeout(walk,0);
}
export function useEcommercePageLanguage(){
 const [lang,setLang]=useState(()=>getEcommerceLanguage());
 useEffect(()=>{
  const onLanguageChange=e=>setLang(e?.detail?.language||getEcommerceLanguage());
  window.addEventListener(EC_LANG_EVENT,onLanguageChange);
  return()=>window.removeEventListener(EC_LANG_EVENT,onLanguageChange);
 },[]);
 useEffect(()=>{applyEcommerceLanguage(lang)},[lang]);
 return lang;
}
